@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem
rem The tree being frozen is not the only thing that must hold still during a
rem qualification. So must the script driving it.
rem ---------------------------------------------------------------------
rem
rem P16-CMD-001 qualification: the exact invocation, recorded so the run is
rem reproducible rather than described.
rem
rem qualify.cmd is carried UNCHANGED from P15-QUAL-001, byte for byte
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b);
rem verify-harness.cmd beside it is its regression and is meant to be run
rem whenever it is edited, which it was not.
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried from INFRA-VIEWER-001 and for the
rem same reason: this machine has 16 logical cores, so `cmake --build` lets
rem Ninja run 18 compiles at once, and a CLEAN build of nearly 600
rem template-heavy translation units exhausted the commit charge --
rem "cc1plus.exe: out of memory allocating 4198399 bytes", at object 286 of
rem 592. ONE resource failure became FIVE failed stages there. Capping
rem parallelism weakens nothing: the same sources are compiled with the same
rem flags, -Werror included, the no-op rebuild check still proves the binaries
rem are the ones just built, the full suite still runs in all three presets,
rem and the determinism stages still repeat five times. Only the number of
rem compilers running at once changes. ctest stays at -j 8.
rem
rem THE REPEAT FILTER IS THE BLAST RADIUS. This milestone puts canonical
rem meshing intent into the Document and rides the SHARED command framework,
rem so the determinism set reaches well past the meshing module:
rem
rem   unit\.Mesh                 the new MeshControl and MeshingCommand tests,
rem                              and every meshing and mesh-renderer test they
rem                              sit beside -- MeshControl delegates validation
rem                              to P16-SIZE's and P16-QUALITY's validators, so
rem                              a change in either surfaces here
rem   unit\.Command              CommandHistory and the framework contract the
rem                              ten new commands depend on: redo clears, a
rem                              failed execute is discarded, depth limits
rem   unit\.AddObjectCommand     the two generic commands the create and delete
rem   unit\.DeleteObjectCommand  commands wrap -- and the ones whose clone()/ID
rem                              requirement this milestone's probe uncovered
rem   unit\.MaterialCommand      the precedent module on the same framework; a
rem                              framework regression shows here too, and not
rem                              only in the new code
rem   unit\.Document             modifyObject's type check and the revision
rem                              rule a no-op edit depends on
rem   unit\.IDs                  core/Id.hpp gained MeshControlId and its
rem   unit\.IdAllocator          document-object trait; allocation must stay
rem                              never-reusing
rem   unit\.DependencyGraph      MeshControl::dependencies() makes a control a
rem                              graph node that depends on its body
rem   gui\.                      the application links the renderer header this
rem                              milestone annotates, and is the integration
rem                              surface for the staleness boundary (A3)
rem   compile_fail               the new meshcmd group: a command CANNOT hold a
rem                              mesh, and the identity confusions
rem   architecture               containment and layering with three new
rem                              meshing sources
rem
rem It is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%: a %VAR%
rem holding | ( or ) is substituted when the for-block is PARSED and closes the
rem block early, killing the run after every preset has already passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=unit\.Mesh|unit\.Command|unit\.AddObjectCommand|unit\.DeleteObjectCommand|unit\.MaterialCommand|unit\.Document|unit\.IDs|unit\.IdAllocator|unit\.DependencyGraph|gui\.|compile_fail|architecture"
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
