@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P16-CLI-001 qualification: the exact invocation, recorded so the run is
rem reproducible rather than described.
rem
rem qualify.cmd is carried UNCHANGED from P15-QUAL-001, byte for byte
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b);
rem verify-harness.cmd beside it is its regression and is meant to be run
rem whenever it is edited, which it was not.
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of nearly 600 template-heavy
rem translation units exhausted the commit charge -- "cc1plus.exe: out of
rem memory allocating 4198399 bytes", at object 286 of 592. ONE resource
rem failure became FIVE failed stages there. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE REPEAT FILTER IS THE BLAST RADIUS.
rem
rem This milestone adds a CLI surface over the P16 meshing core and changes one
rem core file: src/meshing/netgen/NetgenBackend.cpp gains a scope that silences
rem the backend's console output, because Netgen writes to STDOUT and that made
rem the CLI's structured output unparseable (ADVERSARIAL_REVIEW finding C1). It
rem also exports parseNamedFace from the CLI's Selectors.hpp, which every
rem drawing and mate selector already goes through.
rem
rem So the determinism set is:
rem
rem   unit\.MeshingCli      the new CLI tests, including the core/CLI
rem                         equivalence and determinism gates
rem   cli\.                 EVERY cli test, not just the mesh ones: the new
rem                         commands share kCommands, the edit registry, the
rem                         argument parser and Selectors.cpp with all of them,
rem                         and parseNamedFace is now exported from a header
rem                         they all include
rem   unit\.Mesh            every meshing and mesh-renderer test, because the
rem                         backend file changed. A console-silencing scope
rem                         cannot alter a mesh, and this is what proves it
rem   unit\.Volume          the volume mesh contract most directly exposed to
rem   unit\.Netgen          the backend change
rem   unit\.Surface
rem   unit\.Tet
rem   unit\.Document        the document the CLI loads and saves
rem   unit\.FaceName        the face grammar the new commands reuse
rem   unit\.FaceReference
rem   unit\.References
rem   gui\.                the application links the same meshing module
rem   architecture          containment, with a new app-to-module dependency
rem
rem compile_fail is excluded: this milestone adds no compile-fail case, and
rem nothing in apps/bettercad_cli/ is included by one. Each of those cases is a
rem real compilation, so five rounds of roughly two hundred would cost about
rem two hours and report nothing about the CLI. P16-CMD-001 included them
rem because it added thirteen.
rem
rem It is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%: a %VAR%
rem holding | ( or ) is substituted when the for-block is PARSED and closes the
rem block early, killing the run after every preset has already passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=unit\.Mesh|unit\.Volume|unit\.Netgen|unit\.Surface|unit\.Tet|unit\.Document|unit\.FaceName|unit\.FaceReference|unit\.References|cli\.|gui\.|architecture"
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
