@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P16-PERSIST-001 qualification: the exact invocation, recorded so the run is
rem reproducible rather than described.
rem
rem qualify.cmd is carried UNCHANGED from P15-QUAL-001, byte for byte
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b);
rem verify-harness.cmd beside it is its regression and is meant to be run
rem whenever it is edited, which it was not.
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of nearly 600 template-heavy
rem translation units exhausted the commit charge -- "cc1plus.exe: out of
rem memory allocating 4198399 bytes", at object 286 of 592. ONE resource
rem failure became FIVE failed stages there. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE REPEAT FILTER IS THE BLAST RADIUS, AND compile_fail IS DELIBERATELY
rem NOT IN IT.
rem
rem This milestone changes src/io/json/DocumentJson.cpp (the type dispatch) and
rem src/io/json/ObjectJson.hpp, which every *Json.cpp includes -- so every
rem object kind's serialization recompiles, and the realistic risk is the
rem dispatch chain. The determinism set is therefore the whole document
rem format's test surface, not just the new tests:
rem
rem   unit\.Mesh            the new persistence tests, and every meshing and
rem                         mesh-command test whose types the schema writes
rem   unit\.Document        the document format, the header, the allocator
rem   unit\.Material        the precedent object kind in the same dispatch; a
rem                         dispatch regression shows here and not only in the
rem                         new code
rem   unit\.Sketch  unit\.Chamfer  unit\.Fillet  unit\.Hole  unit\.Datum
rem   unit\.Draft   unit\.Shell    unit\.Rib     unit\.Loft  unit\.Sweep
rem   unit\.Revolve unit\.Linear   unit\.Circular unit\.Mirror
rem   unit\.Variable unit\.BodyOps unit\.Through
rem                         every other object kind that goes through the same
rem                         dynamic_cast chain
rem   unit\.FaceReference   the face-reference serialization this schema REUSES
rem   unit\.FaceKind        rather than reimplementing
rem   unit\.References
rem   unit\.Configurations  the optional root sections beside the objects
rem   unit\.Parameter  unit\.Expressions
rem   unit\.Assembly        components and mates, also dispatched
rem   unit\.Export unit\.STEP unit\.STL
rem                         kept although they do not include the changed
rem                         headers: 31 tests, cheaper to include than to
rem                         argue about
rem   cli\.                 the CLI loads documents, and two of these tests are
rem                         this milestone's FRESH-PROCESS evidence
rem   architecture          the new io -> meshing module edge
rem
rem 1359 of 3301 tests. compile_fail is excluded on purpose: this milestone
rem adds no compile-fail case, and ObjectJson.hpp is PRIVATE to io so no
rem compile-fail translation unit can include it. Each of those cases is a real
rem compilation; five rounds of roughly two hundred of them cost about two
rem hours and could not report anything about persistence. P16-CMD-001
rem included them because that milestone added thirteen.
rem
rem It is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%: a %VAR%
rem holding | ( or ) is substituted when the for-block is PARSED and closes the
rem block early, killing the run after every preset has already passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=unit\.Mesh|unit\.Document|unit\.Material|unit\.Sketch|unit\.Chamfer|unit\.Fillet|unit\.Hole|unit\.Datum|unit\.Draft|unit\.Shell|unit\.Rib|unit\.Loft|unit\.Sweep|unit\.Revolve|unit\.Linear|unit\.Circular|unit\.Mirror|unit\.Configurations|unit\.Parameter|unit\.Expressions|unit\.Assembly|unit\.Export|unit\.STEP|unit\.STL|unit\.FaceReference|unit\.FaceKind|unit\.BodyOps|unit\.Through|unit\.Variable|unit\.References|cli\.|architecture"
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
