@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P17-MAT-001 -- Structural Material Resolution. The exact invocation,
rem recorded so the run is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, thirteen in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and was not edited.
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of nearly 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE BLAST RADIUS. Narrower than P17-DATA-001's, and deliberately stated as
rem such: that milestone touched core/Id.hpp and core/math/Vector.hpp, which
rem almost everything includes. This one changes nothing outside structural/,
rem so the reach is the structural module plus whatever reads the analysis
rem definition -- which is the structural module.
rem
rem The repeat set is nonetheless chosen for what this milestone DEPENDS ON
rem rather than what it changed, because the whole milestone is a delegation:
rem
rem   architecture             containment over 455 files, plus the checker
rem                            self-tests
rem   unit\.Structural         this milestone's 19, P17-DATA's 21, P17-ARCH's 10
rem   unit\.Material           P15's material resolution, assignment, custom
rem                            materials, completeness and provenance. THE
rem                            layer every validation is delegated to, so a
rem                            change there is a change to this milestone's
rem                            behaviour even with no structural file touched
rem   unit\.Mass               the other consumer of the same material
rem                            contract, included so a change to it cannot be
rem                            seen from one side only
rem   unit\.Mesh               every meshing and mesh-renderer test, AND
rem                            P16-REFMOD-001's 28 reference cases, which all
rem                            begin "Mesh". The invalidation tests assert
rem                            against P16's currentness API, so its contract
rem                            is in the blast radius
rem   unit\.Volume, unit\.Siz  the volume mesh and sizing contracts
rem   unit\.Id, unit\.Unit, unit\.Quantity
rem                            the identity and unit machinery the solver-ready
rem                            view is built on
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12)
rem   unit\.Analytic           the independent geometry toolkit's own tests
rem   refmod\.                 every reference-model process test
rem   gui\.                    the application links the structural library
rem
rem compile_fail is excluded from the REPEAT for the reason the previous two
rem milestones recorded: each case is a real COMPILATION, so repeating one
rem measures the compiler's determinism and not BetterCAD's. The twelve
rem structural identity cases still run UNFILTERED in all three presets, which
rem is where a compile-fail regression is caught.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Structural|unit\.Material|unit\.Mass|unit\.Mesh|unit\.Volume|unit\.Siz|unit\.Id|unit\.Unit|unit\.Quantity|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
