// P16-PERSIST-001: persisting canonical meshing intent.
//
// THE RULE THESE TESTS EXIST FOR:
//
//     save  ->  meshing intent
//     load  ->  regenerate from current geometry + intent
//
// NOT: save 100,000 tetrahedra and trust them afterwards. So the comparisons
// here are of CANONICAL INTENT, by the same fingerprint P16-CMD-001 uses --
// which reads the body, the deflections, the ordered local controls, the
// ordered boundary sets and the threshold policy, and reads nothing generated.
// A fingerprint that matched because a cached mesh happened to match would be
// no evidence at all.

#include "TestHelpers.hpp"
#include "features/FeatureTestSupport.hpp"
#include "support/TestFiles.hpp"

#include <bettercad/core/Units.hpp>
#include <bettercad/core/document/Document.hpp>
#include <bettercad/core/units/Literals.hpp>
#include <bettercad/features/ExtrudeFeature.hpp>
#include <bettercad/features/Regenerator.hpp>
#include <bettercad/io/DocumentFile.hpp>
#include <bettercad/meshing/MeshControl.hpp>
#include <bettercad/meshing/Mesher.hpp>
#include <bettercad/meshing/MeshingCommands.hpp>
#include <bettercad/sketch/Sketch.hpp>

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>

#include <algorithm>
#include <array>
#include <format>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>

using namespace bettercad;
using namespace bettercad::literals;
using namespace bettercad::test;
using Catch::Matchers::ContainsSubstring;
using meshing::LocalMeshSizing;
using meshing::MeshControl;
using meshing::MeshControlDefinition;
using meshing::NamedBoundarySet;
using meshing::QualityMetric;
using meshing::QualityThreshold;

namespace {

/// The fixture the brief calls for: asymmetric geometry, a global size, two
/// local controls, one resolved reference, one that cannot resolve, and two
/// named boundary sets.
struct Part {
    Document document{"Part"};
    features::Regenerator regenerator;
    ObjectId feature{};
    std::array<EntityId, 4> lines{};

    Part() {
        auto sketch = std::make_unique<sketch::Sketch>("Profile", Frame3D::xy());
        // 30 x 20, not square: an asymmetric body cannot have two faces
        // accidentally interchangeable.
        lines = addRectangle(*sketch, 0_mm, 0_mm, 30_mm, 20_mm);
        const ObjectId profile = require(document.addObject(std::move(sketch)));
        auto extrude = features::ExtrudeFeature::create(
            "Solid", {.profile = SketchId::fromValue(profile.value()), .depth = 10_mm});
        REQUIRE(extrude.has_value());
        feature = require(document.addObject(std::move(*extrude)));
        requireReport(regenerator, document);
    }

    [[nodiscard]] FaceName top() const {
        return FaceName{feature, FaceSelector{.role = FaceRole::EndCap}};
    }
    [[nodiscard]] FaceName bottom() const {
        return FaceName{feature, FaceSelector{.role = FaceRole::StartCap}};
    }
    [[nodiscard]] FaceName side(std::size_t which) const {
        return FaceName{feature, FaceSelector{.role = FaceRole::Side, .entity = lines[which]}};
    }
    /// A reference that is well formed and names an entity no face is
    /// generated by: unresolved, not malformed. The distinction is the whole
    /// of P16-PERSIST's §77.
    [[nodiscard]] FaceName unresolvable() const {
        return FaceName{feature, FaceSelector{.role = FaceRole::Side,
                                              .entity = EntityId::fromValue(9999U)}};
    }
};

/// A cylinder, r 6 x h 20 mm: the fixture that can show a mesh growing.
struct Tube {
    Document document{"Tube"};
    features::Regenerator regenerator;
    ObjectId feature{};

    Tube() {
        auto sketch = std::make_unique<sketch::Sketch>("Profile", Frame3D::xy());
        REQUIRE(sketch->addCircle(Point2D{0_mm, 0_mm}, 6_mm).has_value());
        const ObjectId profile = require(document.addObject(std::move(sketch)));
        auto extrude = features::ExtrudeFeature::create(
            "Solid", {.profile = SketchId::fromValue(profile.value()), .depth = 20_mm});
        REQUIRE(extrude.has_value());
        feature = require(document.addObject(std::move(*extrude)));
        requireReport(regenerator, document);
    }
};

[[nodiscard]] std::string describe(const FaceName& name) {
    const auto id = [](const auto& optional) {
        return optional.has_value() ? std::format("{}", optional->value()) : std::string{"-"};
    };
    std::string text = std::format("{},{},{},{},{},{}", name.feature.value(),
                                   static_cast<int>(name.face.role), id(name.face.entity),
                                   id(name.face.along), id(name.face.alongSketch),
                                   id(name.face.edge));
    for (const FaceCopy& copy : name.face.copies) {
        text += std::format(",copy({},{})", copy.feature.value(), copy.instance);
    }
    return text;
}

/// Canonical meshing intent, and nothing else. The same shape P16-CMD-001's
/// command tests use, so the two milestones compare the same thing.
[[nodiscard]] std::string fingerprint(const MeshControl& control) {
    const MeshControlDefinition& definition = control.definition();
    std::string text = std::format("body={}", definition.body.value());
    text += std::format("|global={}",
                        definition.mesh.sizing.globalTargetSize.has_value()
                            ? std::format("{:.12g}", definition.mesh.sizing.globalTargetSize->si())
                            : std::string{"default"});
    text += std::format("|deflection={:.12g}/{:.12g}",
                        definition.mesh.surface.linearDeflection.si(),
                        definition.mesh.surface.angularDeflection.si());
    for (const LocalMeshSizing& local : control.orderedLocalSizing()) {
        text += std::format("|local[{}]={:.12g}", describe(local.face), local.targetSize.si());
    }
    for (const NamedBoundarySet& set : control.orderedBoundarySets()) {
        text += std::format("|set[{}:{}]=", set.id.value(), set.name);
        for (const FaceName& face : set.faces) {
            text += std::format("({})", describe(face));
        }
    }
    for (const auto& [metric, threshold] : definition.quality.limits) {
        text += std::format("|limit[{}]={:.12g}/{:.12g}", static_cast<int>(metric),
                            threshold.warning.value_or(0.0), threshold.failure.value_or(0.0));
    }
    return text;
}

[[nodiscard]] const MeshControl& onlyControl(const Document& document) {
    const std::vector<MeshControlId> controls = meshing::meshControls(document);
    REQUIRE(controls.size() == 1U);
    const MeshControl* found = meshing::findMeshControl(document, controls.front());
    REQUIRE(found != nullptr);
    return *found;
}

/// The full fixture's definition, built once so every test compares the same
/// intent.
[[nodiscard]] MeshControlDefinition fullDefinition(const Part& part) {
    MeshControlDefinition definition;
    definition.body = part.feature;
    definition.mesh.surface.linearDeflection = Length::fromSi(5e-5);
    definition.mesh.surface.angularDeflection = Angle::fromSi(0.25);
    definition.mesh.sizing.globalTargetSize = 8_mm;
    definition.mesh.sizing.local.push_back(
        LocalMeshSizing{.face = part.side(2), .targetSize = 2_mm});
    definition.mesh.sizing.local.push_back(LocalMeshSizing{.face = part.top(), .targetSize = 1_mm});
    // The one that cannot resolve, carried as intent.
    definition.mesh.sizing.local.push_back(
        LocalMeshSizing{.face = part.unresolvable(), .targetSize = 3_mm});
    definition.quality.limits.emplace(
        QualityMetric::TetMinDihedralAngle,
        QualityThreshold{.warning = 0.3, .failure = 0.1});
    definition.boundarySets.push_back(NamedBoundarySet{
        .id = BoundarySetId::fromValue(4U), .name = "fixed_end", .faces = {part.bottom()}});
    definition.boundarySets.push_back(
        NamedBoundarySet{.id = BoundarySetId::fromValue(2U),
                         .name = "loaded",
                         .faces = {part.side(0), part.side(1)}});
    return definition;
}

[[nodiscard]] MeshControlId addControl(Document& document, std::string name,
                                       MeshControlDefinition definition) {
    auto control = MeshControl::create(std::move(name), std::move(definition));
    INFO((control ? std::string{} : control.error().message));
    REQUIRE(control.has_value());
    const ObjectId id = require(document.addObject(std::move(*control)));
    return MeshControlId::fromValue(id.value());
}

/// Round trips a document through the real file path, not through a string.
[[nodiscard]] Document roundTrip(const Document& document, const std::filesystem::path& file) {
    const Result<void> saved = io::saveDocument(document, file);
    INFO((saved ? std::string{} : saved.error().message));
    REQUIRE(saved.has_value());
    Result<Document> loaded = io::loadDocument(file);
    INFO((loaded ? std::string{} : loaded.error().message));
    REQUIRE(loaded.has_value());
    return std::move(*loaded);
}

/// Replaces the mesh-control object's `data` in a saved file, so a malformed
/// field can be tested without a hand-written whole document.
[[nodiscard]] std::string withControlData(const std::string& json, std::string_view replacement) {
    const std::size_t typeAt = json.find("\"type\": \"mesh-control\"");
    REQUIRE(typeAt != std::string::npos);
    const std::size_t dataAt = json.find("\"data\":", typeAt);
    REQUIRE(dataAt != std::string::npos);
    const std::size_t open = json.find('{', dataAt);
    REQUIRE(open != std::string::npos);
    // Walk to the matching brace, so nested objects are handled.
    std::size_t depth = 0;
    std::size_t close = open;
    for (; close < json.size(); ++close) {
        if (json[close] == '{') {
            ++depth;
        } else if (json[close] == '}') {
            --depth;
            if (depth == 0) {
                break;
            }
        }
    }
    REQUIRE(close < json.size());
    return json.substr(0, open) + std::string{replacement} + json.substr(close + 1);
}

[[nodiscard]] Error loadFailure(std::string_view json) {
    Result<Document> loaded = io::documentFromJson(json);
    REQUIRE_FALSE(loaded.has_value());
    return loaded.error();
}

} // namespace

// ---------------------------------------------------------------------------
// Round trip
// ---------------------------------------------------------------------------

TEST_CASE("MeshingPersistence_TheWholeCanonicalIntentRoundTrips", "[meshing][io][persist]") {
    // The primary qualification fixture: global sizing, three local controls
    // (two resolvable, one not), two boundary sets with one and two faces, a
    // threshold policy, and non-default deflections.
    TempDir temp;
    Part part;
    const MeshControlId control = addControl(part.document, "Mesh", fullDefinition(part));
    const std::string before = fingerprint(onlyControl(part.document));

    const Document loaded = roundTrip(part.document, temp.path() / "full.bcad");
    const std::string after = fingerprint(onlyControl(loaded));

    CHECK(after == before);

    // And the identity survived, so a command or a later reference still
    // finds it.
    CHECK(meshing::findMeshControl(loaded, control) != nullptr);
    CHECK(meshing::findMeshControl(loaded, control)->name() == "Mesh");
}

TEST_CASE("MeshingPersistence_GlobalSizingRoundTripsIncludingItsAbsence",
          "[meshing][io][persist]") {
    TempDir temp;
    Part part;

    SECTION("a target size") {
        MeshControlDefinition definition;
        definition.body = part.feature;
        definition.mesh.sizing.globalTargetSize = 7_mm;
        (void)addControl(part.document, "Mesh", definition);
        const Document loaded = roundTrip(part.document, temp.path() / "global.bcad");
        CHECK(onlyControl(loaded).definition().mesh.sizing.globalTargetSize == 7_mm);
    }

    SECTION("no target size at all") {
        // ABSENT IS A STATE, not a missing number: it means BetterCAD's
        // scale-relative default. It must come back absent rather than as
        // whatever number this build would have chosen.
        MeshControlDefinition definition;
        definition.body = part.feature;
        (void)addControl(part.document, "Mesh", definition);
        const Document loaded = roundTrip(part.document, temp.path() / "default.bcad");
        CHECK_FALSE(onlyControl(loaded).definition().mesh.sizing.globalTargetSize.has_value());
    }
}

TEST_CASE("MeshingPersistence_LocalControlsKeepTheirFaceAndSize", "[meshing][io][persist]") {
    TempDir temp;
    Part part;
    MeshControlDefinition definition;
    definition.body = part.feature;
    definition.mesh.sizing.local.push_back(
        LocalMeshSizing{.face = part.side(1), .targetSize = 1.5_mm});
    definition.mesh.sizing.local.push_back(LocalMeshSizing{.face = part.top(), .targetSize = 4_mm});
    (void)addControl(part.document, "Mesh", definition);

    const Document loaded = roundTrip(part.document, temp.path() / "local.bcad");
    const MeshControl& control = onlyControl(loaded);

    // A LOCAL CONTROL'S IDENTITY IS ITS FACE (P16-SIZE-001), so "the same
    // control came back" means the same FaceName resolves to the same size.
    REQUIRE(control.localSizing(part.side(1)) != nullptr);
    CHECK(control.localSizing(part.side(1))->targetSize == 1.5_mm);
    CHECK(control.localSizing(part.side(1))->face == part.side(1));
    REQUIRE(control.localSizing(part.top()) != nullptr);
    CHECK(control.localSizing(part.top())->targetSize == 4_mm);
    CHECK(control.definition().mesh.sizing.local.size() == 2U);
}

TEST_CASE("MeshingPersistence_BoundarySetsKeepTheirIdentityNameAndOrder",
          "[meshing][io][persist]") {
    TempDir temp;
    Part part;
    MeshControlDefinition definition;
    definition.body = part.feature;
    // Added out of ID order, so the file's order cannot be the insertion
    // order by accident.
    definition.boundarySets.push_back(NamedBoundarySet{
        .id = BoundarySetId::fromValue(9U), .name = "outlet", .faces = {part.top()}});
    definition.boundarySets.push_back(
        NamedBoundarySet{.id = BoundarySetId::fromValue(3U),
                         .name = "inlet",
                         .faces = {part.side(0), part.bottom(), part.side(2)}});
    (void)addControl(part.document, "Mesh", definition);

    const Document loaded = roundTrip(part.document, temp.path() / "sets.bcad");
    const MeshControl& control = onlyControl(loaded);

    const NamedBoundarySet* outlet = control.boundarySet(BoundarySetId::fromValue(9U));
    const NamedBoundarySet* inlet = control.boundarySet(BoundarySetId::fromValue(3U));
    REQUIRE(outlet != nullptr);
    REQUIRE(inlet != nullptr);
    // THE SAME IDs, not new ones: a set that came back renumbered would break
    // every reference to it.
    CHECK(outlet->id == BoundarySetId::fromValue(9U));
    CHECK(outlet->name == "outlet");
    CHECK(inlet->name == "inlet");
    // The FACE ORDER inside a set is the user's sequence and is preserved,
    // unlike the stored order of local controls.
    REQUIRE(inlet->faces.size() == 3U);
    CHECK(inlet->faces[0] == part.side(0));
    CHECK(inlet->faces[1] == part.bottom());
    CHECK(inlet->faces[2] == part.side(2));
}

TEST_CASE("MeshingPersistence_EveryQualityMetricRoundTrips", "[meshing][io][persist]") {
    // THE GUARD ON THE METRIC NAME TABLE. `metricName` falls back to "unknown"
    // for a metric missing from it, which would serialize silently and then
    // fail to load. Putting a threshold on each metric in turn is what makes
    // that loud: add a metric to the enum without a file key and this fails.
    //
    // The bounds are chosen per direction so validate(QualityThresholds)
    // accepts them: for a higher-is-better metric a failure bound must not
    // exceed its warning bound, and for lower-is-better the reverse.
    constexpr std::array<QualityMetric, 18> all{
        QualityMetric::TetVolume,              QualityMetric::TetJacobianDeterminant,
        QualityMetric::TetMinEdgeLength,       QualityMetric::TetMaxEdgeLength,
        QualityMetric::TetMeanEdgeLength,      QualityMetric::TetAspectRatio,
        QualityMetric::TetRadiusRatio,         QualityMetric::TetInradius,
        QualityMetric::TetCircumradius,        QualityMetric::TetMinDihedralAngle,
        QualityMetric::TetMaxDihedralAngle,    QualityMetric::TriangleArea,
        QualityMetric::TriangleMinEdgeLength,  QualityMetric::TriangleMaxEdgeLength,
        QualityMetric::TriangleMeanEdgeLength, QualityMetric::TriangleShapeQuality,
        QualityMetric::TriangleMinAngle,       QualityMetric::TriangleMaxAngle};

    // ONLY SEVEN OF THE EIGHTEEN CAN CARRY A THRESHOLD, and the other eleven
    // are not an omission: a dimensioned size has no scale-free good
    // direction, so P16-QUALITY-001 classifies it ContextOnly and
    // validate(QualityThresholds) refuses a bound on it. A ContextOnly
    // threshold therefore cannot exist in a document, let alone in a file --
    // asserted below rather than assumed.
    //
    // The bounds have to follow each metric's direction: for higher-is-better
    // a failure bound must not exceed its warning bound, and for
    // lower-is-better the reverse. One pair of numbers for all of them was the
    // first version of this test, and it silently exercised only four.
    constexpr std::array<QualityMetric, 7> classifiable{
        QualityMetric::TetRadiusRatio,      QualityMetric::TetMinDihedralAngle,
        QualityMetric::TriangleShapeQuality, QualityMetric::TriangleMinAngle,
        QualityMetric::TetAspectRatio,      QualityMetric::TetMaxDihedralAngle,
        QualityMetric::TriangleMaxAngle};
    const auto higherIsBetter = [](QualityMetric metric) {
        return metric == QualityMetric::TetRadiusRatio ||
               metric == QualityMetric::TetMinDihedralAngle ||
               metric == QualityMetric::TriangleShapeQuality ||
               metric == QualityMetric::TriangleMinAngle;
    };

    TempDir temp;
    std::size_t accepted = 0;
    for (const QualityMetric metric : classifiable) {
        Part part;
        MeshControlDefinition definition;
        definition.body = part.feature;
        definition.quality.limits.emplace(
            metric, higherIsBetter(metric) ? QualityThreshold{.warning = 0.4, .failure = 0.2}
                                           : QualityThreshold{.warning = 0.4, .failure = 0.6});
        auto control = MeshControl::create("Mesh", definition);
        INFO("metric " << static_cast<int>(metric));
        REQUIRE(control.has_value());
        (void)require(part.document.addObject(std::move(*control)));
        const std::string before = fingerprint(onlyControl(part.document));

        // THE FILE NAMES IT, by a key that is not the "unknown" fallback. A
        // metric added to the enum without a file key fails here.
        const Result<std::string> text = io::documentToJson(part.document);
        REQUIRE(text.has_value());
        CHECK_THAT(*text, !ContainsSubstring("\"unknown\""));

        const Document loaded =
            roundTrip(part.document, temp.path() / std::format("metric-{}.bcad",
                                                               static_cast<int>(metric)));
        CHECK(fingerprint(onlyControl(loaded)) == before);
        ++accepted;
    }
    CHECK(accepted == classifiable.size());

    // And a ContextOnly metric's threshold is refused by the core, so it never
    // reaches a file at all. Eleven of the eighteen, checked by difference so
    // that adding a metric without deciding its direction shows up.
    std::size_t contextOnly = 0;
    for (const QualityMetric metric : all) {
        if (std::ranges::find(classifiable, metric) != classifiable.end()) {
            continue;
        }
        Part part;
        MeshControlDefinition definition;
        definition.body = part.feature;
        definition.quality.limits.emplace(metric,
                                          QualityThreshold{.warning = 0.4, .failure = 0.2});
        INFO("metric " << static_cast<int>(metric));
        CHECK_FALSE(MeshControl::create("Mesh", definition).has_value());
        ++contextOnly;
    }
    CHECK(contextOnly == all.size() - classifiable.size());
}

TEST_CASE("MeshingPersistence_SurfaceDeflectionsRoundTripExactly", "[meshing][io][persist]") {
    TempDir temp;
    Part part;
    MeshControlDefinition definition;
    definition.body = part.feature;
    definition.mesh.surface.linearDeflection = Length::fromSi(1.25e-5);
    definition.mesh.surface.angularDeflection = Angle::fromSi(0.1234567890123);
    (void)addControl(part.document, "Mesh", definition);

    const Document loaded = roundTrip(part.document, temp.path() / "surface.bcad");
    const meshing::SurfaceMeshControls& surface = onlyControl(loaded).definition().mesh.surface;
    // EXACT. The format writes a double and reads it back; a serializer that
    // lost precision here would change the boundary discretisation.
    CHECK(surface.linearDeflection == Length::fromSi(1.25e-5));
    CHECK(surface.angularDeflection == Angle::fromSi(0.1234567890123));
}

// ---------------------------------------------------------------------------
// Units
// ---------------------------------------------------------------------------

TEST_CASE("MeshingPersistence_EngineeringLengthsSurviveWithoutAFactorOfAThousand",
          "[meshing][io][persist][units]") {
    // The document format stores bare SI doubles -- metres -- so this is a
    // test that the SI boundary is crossed exactly once, in each direction.
    // A factor of 1000 is the failure mode that would look plausible in a
    // file and be catastrophic in a mesh.
    TempDir temp;
    const std::array<Length, 5> sizes{1_mm, 10_mm, Length::fromSi(1.0), Length::fromSi(0.001),
                                      Length::fromSi(0.0125)};
    for (const Length size : sizes) {
        Part part;
        MeshControlDefinition definition;
        definition.body = part.feature;
        definition.mesh.sizing.globalTargetSize = size;
        definition.mesh.sizing.local.push_back(
            LocalMeshSizing{.face = part.top(), .targetSize = size});
        (void)addControl(part.document, "Mesh", definition);

        const Document loaded =
            roundTrip(part.document, temp.path() / std::format("unit-{:.6g}.bcad", size.si()));
        const MeshControl& control = onlyControl(loaded);
        INFO(std::format("{} m", size.si()));
        // EXACT canonical equality, both globally and locally.
        CHECK(control.definition().mesh.sizing.globalTargetSize == size);
        REQUIRE(control.localSizing(part.top()) != nullptr);
        CHECK(control.localSizing(part.top())->targetSize == size);
    }

    // And 10 mm really is written as 0.01, not as 10: the one assertion that
    // pins the file's unit rather than only the round trip's consistency. A
    // serializer writing millimetres would round-trip perfectly and still be
    // wrong for every other reader of the format.
    Part part;
    MeshControlDefinition definition;
    definition.body = part.feature;
    definition.mesh.sizing.globalTargetSize = 10_mm;
    (void)addControl(part.document, "Mesh", definition);
    const Result<std::string> json = io::documentToJson(part.document);
    REQUIRE(json.has_value());
    CHECK_THAT(*json, ContainsSubstring("\"target_size\": 0.01"));
}

// ---------------------------------------------------------------------------
// Deterministic serialization
// ---------------------------------------------------------------------------

TEST_CASE("MeshingPersistence_SerializationIsByteIdenticalAndIndependentOfEditOrder",
          "[meshing][io][persist][determinism]") {
    // `Json` is nlohmann::ordered_json, so the file's order is the insertion
    // order -- determinism is something this schema has to earn rather than
    // get. Earned by writing every collection through MeshControl's ordered
    // accessors.
    const auto build = [](const Part& part, bool reversed) {
        MeshControlDefinition definition;
        definition.body = part.feature;
        definition.mesh.sizing.globalTargetSize = 6_mm;
        std::vector<LocalMeshSizing> local{
            LocalMeshSizing{.face = part.side(2), .targetSize = 2_mm},
            LocalMeshSizing{.face = part.top(), .targetSize = 1_mm},
            LocalMeshSizing{.face = part.side(0), .targetSize = 3_mm}};
        std::vector<NamedBoundarySet> sets{
            NamedBoundarySet{
                .id = BoundarySetId::fromValue(7U), .name = "b", .faces = {part.top()}},
            NamedBoundarySet{
                .id = BoundarySetId::fromValue(1U), .name = "a", .faces = {part.bottom()}}};
        if (reversed) {
            std::ranges::reverse(local);
            std::ranges::reverse(sets);
        }
        definition.mesh.sizing.local = std::move(local);
        definition.boundarySets = std::move(sets);
        return definition;
    };

    Part first;
    (void)addControl(first.document, "Mesh", build(first, false));
    const Result<std::string> one = io::documentToJson(first.document);
    REQUIRE(one.has_value());

    // Saving the SAME document again must give the same bytes.
    const Result<std::string> again = io::documentToJson(first.document);
    REQUIRE(again.has_value());
    CHECK(*again == *one);

    // And a document built with the controls added in the OPPOSITE order must
    // give the same bytes too, because their stored order carries no meaning.
    Part second;
    (void)addControl(second.document, "Mesh", build(second, true));
    const Result<std::string> reversed = io::documentToJson(second.document);
    REQUIRE(reversed.has_value());
    // The documents differ in their UUID and object ids, so compare the
    // mesh-control section rather than the whole file.
    const auto controlSection = [](const std::string& text) {
        const std::size_t at = text.find("\"type\": \"mesh-control\"");
        REQUIRE(at != std::string::npos);
        return text.substr(at);
    };
    CHECK(controlSection(*reversed) == controlSection(*one));
}

TEST_CASE("MeshingPersistence_SaveLoadSaveIsByteIdentical", "[meshing][io][persist][determinism]") {
    TempDir temp;
    Part part;
    (void)addControl(part.document, "Mesh", fullDefinition(part));

    const std::filesystem::path first = temp.path() / "f1.bcad";
    const std::filesystem::path second = temp.path() / "f2.bcad";
    REQUIRE(io::saveDocument(part.document, first).has_value());
    Result<Document> loaded = io::loadDocument(first);
    INFO((loaded ? std::string{} : loaded.error().message));
    REQUIRE(loaded.has_value());
    REQUIRE(io::saveDocument(*loaded, second).has_value());

    // F1 == F2, byte for byte. This is what makes the format reproducible:
    // a document that has been through a load is written exactly as it came.
    CHECK(readFile(first) == readFile(second));

    // Three times, so a difference that only appears on a later pass shows.
    Result<Document> twice = io::loadDocument(second);
    REQUIRE(twice.has_value());
    const std::filesystem::path third = temp.path() / "f3.bcad";
    REQUIRE(io::saveDocument(*twice, third).has_value());
    CHECK(readFile(third) == readFile(first));
}

// ---------------------------------------------------------------------------
// The derived-state boundary
// ---------------------------------------------------------------------------

TEST_CASE("MeshingPersistence_NoGeneratedMeshReachesTheFile", "[meshing][io][persist][authority]") {
    // A STRUCTURAL CHECK OF THE WRITTEN BYTES, not an argument from the code.
    // The mesh is generated first, so there is something that could leak.
    TempDir temp;
    Part part;
    const MeshControlId control = addControl(part.document, "Mesh", fullDefinition(part));

    meshing::Mesher mesher;
    // The fixture's unresolvable control makes meshing refuse, which is
    // P16-CMD-001's contract; mesh a second control that can resolve, so a
    // real mesh exists in the process when the document is saved.
    MeshControlDefinition meshable;
    meshable.body = part.feature;
    meshable.mesh.sizing.globalTargetSize = 4_mm;
    const MeshControlId good = addControl(part.document, "Meshable", meshable);
    const Result<const meshing::VolumeMesh*> generated =
        mesher.generate(part.document, part.regenerator, good);
    INFO((generated ? std::string{} : generated.error().message));
    REQUIRE(generated.has_value());
    REQUIRE((*generated)->mesh().elementCount() > 0U);
    (void)control;

    const std::filesystem::path file = temp.path() / "authority.bcad";
    REQUIRE(io::saveDocument(part.document, file).has_value());
    const std::string text = readFile(file);

    // Nothing generated is in the file, by name.
    for (const std::string_view forbidden :
         {"nodes", "tetrahedra", "triangles", "elements", "node_id", "element_id", "facet",
          "connectivity", "netgen", "quality_report", "worst", "render", "ng_mesh"}) {
        INFO(forbidden);
        CHECK(text.find(forbidden) == std::string::npos);
    }
    // And the keys that SHOULD be there are, so the test is not passing
    // because nothing was written at all.
    CHECK_THAT(text, ContainsSubstring("\"mesh-control\""));
    CHECK_THAT(text, ContainsSubstring("\"target_size\""));
    CHECK_THAT(text, ContainsSubstring("\"boundary_sets\""));
}

TEST_CASE("MeshingPersistence_FileSizeDoesNotFollowMeshDensity",
          "[meshing][io][persist][authority]") {
    // THE MEASUREMENT BEHIND THE CLAIM. Same canonical intent except the
    // target size; the meshes differ by thousands of elements; the files must
    // not. A format persisting elements would differ by megabytes.
    TempDir temp;
    const auto saveAt = [&temp](Length target, const char* label) {
        // A CYLINDER, because a block cannot demonstrate this: its boundary is
        // planar and exactly representable, so 10 mm and 1.2 mm both give 24
        // tetrahedra (P16-SIZE-001 recorded the same thing, and P16-CMD-001's
        // payload test hit it too). Without a curved wall there is no mesh
        // growth for the file size to be independent OF.
        Tube part;
        MeshControlDefinition definition;
        definition.body = part.feature;
        definition.mesh.sizing.globalTargetSize = target;
        const MeshControlId control = addControl(part.document, "Mesh", definition);

        meshing::Mesher mesher;
        const Result<const meshing::VolumeMesh*> mesh =
            mesher.generate(part.document, part.regenerator, control);
        INFO((mesh ? std::string{} : mesh.error().message));
        REQUIRE(mesh.has_value());
        const std::size_t elements = (*mesh)->mesh().elementCount();

        const std::filesystem::path file = temp.path() / std::format("{}.bcad", label);
        REQUIRE(io::saveDocument(part.document, file).has_value());
        return std::pair{elements, readFile(file).size()};
    };

    const auto [coarseElements, coarseBytes] = saveAt(10_mm, "coarse");
    const auto [fineElements, fineBytes] = saveAt(1.2_mm, "fine");

    // The refinement must have done something, or the comparison is empty.
    REQUIRE(fineElements > coarseElements);
    // The two files differ only in the digits of one number, so a handful of
    // bytes. A tolerance of 64 is generous and still three orders of
    // magnitude below what persisting even the COARSE mesh would cost.
    const std::size_t difference =
        fineBytes > coarseBytes ? fineBytes - coarseBytes : coarseBytes - fineBytes;
    CHECK(difference < 64U);
    WARN(std::format("coarse {} elements -> {} bytes | fine {} elements -> {} bytes | "
                     "file difference {} bytes",
                     coarseElements, coarseBytes, fineElements, fineBytes, difference));
}

// ---------------------------------------------------------------------------
// Malformed input
// ---------------------------------------------------------------------------

TEST_CASE("MeshingPersistence_RejectsMalformedMeshingIntent", "[meshing][io][persist][malformed]") {
    Part part;
    (void)addControl(part.document, "Mesh", fullDefinition(part));
    const Result<std::string> good = io::documentToJson(part.document);
    REQUIRE(good.has_value());
    // The valid file loads, or every rejection below could be for the wrong
    // reason.
    REQUIRE(io::documentFromJson(*good).has_value());

    const ObjectId body = part.feature;
    const auto data = [body](std::string_view extra) {
        return std::format(R"({{"body": {}, "surface": {{"linear_deflection": 0.0001,
            "angular_deflection": 0.3}}, "sizing": {{{}}}}})",
                           body.value(), extra);
    };

    SECTION("a zero global size") {
        const Error error = loadFailure(withControlData(*good, data(R"("target_size": 0.0)")));
        CHECK(error.code == ErrorCode::InvalidArgument);
        CHECK_THAT(error.message, ContainsSubstring("positive"));
    }
    SECTION("a negative global size") {
        const Error error = loadFailure(withControlData(*good, data(R"("target_size": -0.001)")));
        CHECK(error.code == ErrorCode::InvalidArgument);
    }
    SECTION("a non-finite global size cannot even be expressed") {
        // MEASURED, AND NOT WHAT I FIRST ASSUMED. `readNumber` only checks
        // is_number(), so the expectation was that 1e999 would arrive as an
        // infinity and be caught by the core validator. It never gets that
        // far: nlohmann's parser throws out_of_range for a number that
        // overflows a double, and `parseJson` maps that to ParseError. The
        // bare literals NaN and Infinity are not JSON at all.
        //
        // So the format cannot carry a non-finite number by any of these
        // routes. The core's finiteness check is a second line of defence
        // rather than the only one -- which is better, and worth recording
        // accurately instead of claiming a defence the file never tests.
        for (const std::string_view literal : {"1e999", "-1e999", "NaN", "Infinity", "-Infinity"}) {
            INFO(literal);
            const Error error = loadFailure(
                withControlData(*good, data(std::format(R"("target_size": {})", literal))));
            CHECK(error.code == ErrorCode::ParseError);
            CHECK_THAT(error.message, ContainsSubstring("invalid JSON"));
        }
    }
    SECTION("a non-numeric size") {
        const Error error = loadFailure(withControlData(*good, data(R"("target_size": "large")")));
        CHECK_THAT(error.message, ContainsSubstring("expected a number"));
    }
    SECTION("an unknown field") {
        const Error error =
            loadFailure(withControlData(*good, data(R"("target_size": 0.01, "netgen_maxh": 3)")));
        CHECK_THAT(error.message, ContainsSubstring("unknown field"));
    }
    SECTION("a missing required field") {
        const Error error = loadFailure(withControlData(
            *good, std::format(R"({{"body": {}, "sizing": {{}}}})", body.value())));
        CHECK_THAT(error.message, ContainsSubstring("missing required field"));
        CHECK_THAT(error.message, ContainsSubstring("surface"));
    }
    SECTION("an invalid body handle") {
        const Error error = loadFailure(withControlData(
            *good, std::format(R"({{"body": 0, "surface": {{"linear_deflection": 0.0001,
                "angular_deflection": 0.3}}, "sizing": {{}}}})")));
        CHECK(error.code == ErrorCode::InvalidArgument);
    }
}

TEST_CASE("MeshingPersistence_RejectsDuplicateIdentitiesRatherThanMerging",
          "[meshing][io][persist][malformed]") {
    Part part;
    (void)addControl(part.document, "Mesh", fullDefinition(part));
    const Result<std::string> good = io::documentToJson(part.document);
    REQUIRE(good.has_value());

    const std::string prefix =
        std::format(R"("body": {}, "surface": {{"linear_deflection": 0.0001,
            "angular_deflection": 0.3}}, )",
                    part.feature.value());
    const std::string face =
        std::format(R"({{"feature": {}, "face": {{"role": "end_cap"}}}})", part.feature.value());

    SECTION("two local controls on one face") {
        // P16-SIZE-001's DuplicateFaceControl, reached through the file. A
        // silent merge or a renumber would be the wrong answer; so would
        // keeping one.
        const Error error = loadFailure(withControlData(
            *good, std::format(R"({{{}"sizing": {{"local": [
                {{"face": {}, "target_size": 0.002}},
                {{"face": {}, "target_size": 0.003}}]}}}})",
                               prefix, face, face)));
        CHECK(error.code == ErrorCode::InvalidArgument);
    }
    SECTION("two boundary sets sharing an identity") {
        const Error error = loadFailure(withControlData(
            *good, std::format(R"({{{}"sizing": {{}}, "boundary_sets": [
                {{"id": 5, "name": "a", "faces": [{}]}},
                {{"id": 5, "name": "b", "faces": [{}]}}]}})",
                               prefix, face, face)));
        CHECK(error.code == ErrorCode::AlreadyExists);
        CHECK_THAT(error.message, ContainsSubstring("identity"));
    }
    SECTION("one metric given a threshold twice") {
        const Error error = loadFailure(withControlData(
            *good, std::format(R"({{{}"sizing": {{}}, "quality": {{"limits": [
                {{"metric": "tet_radius_ratio", "warning": 0.4}},
                {{"metric": "tet_radius_ratio", "warning": 0.5}}]}}}})",
                               prefix)));
        CHECK_THAT(error.message, ContainsSubstring("twice"));
    }
    SECTION("an unknown quality metric") {
        const Error error = loadFailure(withControlData(
            *good, std::format(R"({{{}"sizing": {{}}, "quality": {{"limits": [
                {{"metric": "tet_wishful_thinking", "warning": 0.4}}]}}}})",
                               prefix)));
        CHECK_THAT(error.message, ContainsSubstring("unknown quality metric"));
    }
}

TEST_CASE("MeshingPersistence_AMalformedReferenceIsNotTheSameAsAnUnresolvedOne",
          "[meshing][io][persist][malformed]") {
    // THE DISTINCTION THAT MATTERS MOST (§77). A well-formed reference naming
    // a face that does not currently exist is legitimate intent and must
    // load; a reference whose ENCODING is wrong is corruption and must not.
    Part part;
    (void)addControl(part.document, "Mesh", fullDefinition(part));
    const Result<std::string> good = io::documentToJson(part.document);
    REQUIRE(good.has_value());
    const std::string prefix =
        std::format(R"("body": {}, "surface": {{"linear_deflection": 0.0001,
            "angular_deflection": 0.3}}, )",
                    part.feature.value());

    SECTION("a malformed selector is rejected") {
        const Error error = loadFailure(withControlData(
            *good, std::format(R"({{{}"sizing": {{"local": [
                {{"face": {{"feature": {}, "face": {{"role": "sideways"}}}},
                 "target_size": 0.002}}]}}}})",
                               prefix, part.feature.value())));
        CHECK_THAT(error.message, ContainsSubstring("unknown value"));
    }
    SECTION("a side face naming no entity is rejected by the selector's own rule") {
        // validate(FaceSelector): a side face must name a valid entity. The
        // refusal arrives as a ParseError, not an InvalidArgument, because
        // faceNameFromJson classifies a selector it cannot interpret as bad
        // FILE CONTENT -- which is the right category for it and is how every
        // other reference in the format reports the same mistake.
        const Error error = loadFailure(withControlData(
            *good, std::format(R"({{{}"sizing": {{"local": [
                {{"face": {{"feature": {}, "face": {{"role": "side"}}}},
                 "target_size": 0.002}}]}}}})",
                               prefix, part.feature.value())));
        CHECK(error.code == ErrorCode::ParseError);
        CHECK_THAT(error.message, ContainsSubstring("local"));
    }
    SECTION("a well-formed reference to an absent face LOADS") {
        const Error* none = nullptr;
        (void)none;
        Result<Document> loaded = io::documentFromJson(withControlData(
            *good, std::format(R"({{{}"sizing": {{"local": [
                {{"face": {{"feature": {}, "face": {{"role": "side", "entity": 9999}}}},
                 "target_size": 0.002}}]}}}})",
                               prefix, part.feature.value())));
        INFO((loaded ? std::string{} : loaded.error().message));
        REQUIRE(loaded.has_value());
        const MeshControl& control = onlyControl(*loaded);
        const FaceName absent{part.feature,
                              FaceSelector{.role = FaceRole::Side,
                                           .entity = EntityId::fromValue(9999U)}};
        REQUIRE(control.localSizing(absent) != nullptr);
        CHECK(control.localSizing(absent)->face == absent);
    }
}

TEST_CASE("MeshingPersistence_ACorruptFileLeavesTheOpenDocumentAlone",
          "[meshing][io][persist][malformed]") {
    // Load atomicity is structural -- documentFromJson builds a NEW document
    // -- and this is the test that makes that a verified property rather than
    // a reading of the signature.
    TempDir temp;
    Part part;
    (void)addControl(part.document, "Mesh", fullDefinition(part));
    const std::string before = fingerprint(onlyControl(part.document));
    const std::uint64_t revision = part.document.revision();

    const Result<std::string> good = io::documentToJson(part.document);
    REQUIRE(good.has_value());

    for (const std::string& broken : {good->substr(0, good->size() / 2),  // truncated
                                     std::string{"{\"format\": "},       // unterminated
                                     std::string{"not json at all"},
                                     std::string{"[]"}}) {
        INFO(broken.substr(0, 40));
        CHECK_FALSE(io::documentFromJson(broken).has_value());
        // The open document is untouched by the attempt.
        CHECK(fingerprint(onlyControl(part.document)) == before);
        CHECK(part.document.revision() == revision);
    }

    // And a file that cannot be read at all fails without touching anything.
    CHECK_FALSE(io::loadDocument(temp.path() / "there-is-no-such-file.bcad").has_value());
    CHECK(fingerprint(onlyControl(part.document)) == before);
}

// ---------------------------------------------------------------------------
// Compatibility
// ---------------------------------------------------------------------------

TEST_CASE("MeshingPersistence_APreP16DocumentLoadsAndSimplyHasNoControls",
          "[meshing][io][persist][compat]") {
    // Adding an object type needs no version bump, which is the format's own
    // rule. The consequence to verify is that an older document is not
    // refused for lacking something it never had: there is no meshing SECTION
    // to be absent, because a control is an entry in `objects`.
    TempDir temp;
    Part part;  // no mesh control at all
    const std::filesystem::path file = temp.path() / "pre-p16.bcad";
    REQUIRE(io::saveDocument(part.document, file).has_value());
    const std::string text = readFile(file);
    REQUIRE(text.find("mesh-control") == std::string::npos);
    CHECK_THAT(text, ContainsSubstring("\"version\": 2"));

    Result<Document> loaded = io::loadDocument(file);
    INFO((loaded ? std::string{} : loaded.error().message));
    REQUIRE(loaded.has_value());
    CHECK(meshing::meshControls(*loaded).empty());

    // A version-1 document loads too, and also gains no controls.
    std::string older = text;
    const std::size_t at = older.find("\"version\": 2");
    REQUIRE(at != std::string::npos);
    older.replace(at, std::string_view{"\"version\": 2"}.size(), "\"version\": 1");
    Result<Document> legacy = io::documentFromJson(older);
    INFO((legacy ? std::string{} : legacy.error().message));
    REQUIRE(legacy.has_value());
    CHECK(meshing::meshControls(*legacy).empty());
}

TEST_CASE("MeshingPersistence_AnUnknownObjectTypeIsRefusedByName",
          "[meshing][io][persist][compat]") {
    // The forward-compatibility boundary: an older build meeting a newer file
    // refuses and says what it did not recognise, rather than skipping the
    // object and silently losing engineering intent.
    Part part;
    (void)addControl(part.document, "Mesh", fullDefinition(part));
    const Result<std::string> good = io::documentToJson(part.document);
    REQUIRE(good.has_value());

    std::string renamed = *good;
    const std::size_t at = renamed.find("\"mesh-control\"");
    REQUIRE(at != std::string::npos);
    renamed.replace(at, std::string_view{"\"mesh-control\""}.size(), "\"mesh-control-v2\"");
    const Error error = loadFailure(renamed);
    CHECK_THAT(error.message, ContainsSubstring("unknown object type"));
    CHECK_THAT(error.message, ContainsSubstring("mesh-control-v2"));
}

TEST_CASE("MeshingPersistence_TheFileNeedsNoMeshingBackendToBeInterpreted",
          "[meshing][io][persist][compat]") {
    // Backend independence, checked against the bytes. Nothing in the file
    // should name Netgen or carry a backend parameter: the canonical schema is
    // BetterCAD's, and the mapping to a backend is an implementation detail
    // that a future backend change must be free to alter.
    Part part;
    (void)addControl(part.document, "Mesh", fullDefinition(part));
    const Result<std::string> json = io::documentToJson(part.document);
    REQUIRE(json.has_value());
    for (const std::string_view forbidden :
         {"netgen", "nglib", "maxh", "minh", "grading", "Ng_", "second_order", "optimize"}) {
        INFO(forbidden);
        CHECK(json->find(forbidden) == std::string::npos);
    }
}

// ---------------------------------------------------------------------------
// Regenerate after load
// ---------------------------------------------------------------------------
//
// The milestone's hard gate. A loaded document carries intent and NO mesh; the
// mesh comes from the loaded geometry plus the loaded intent, on request. What
// these tests compare is the mesh SEMANTICS, never a mesh identity: NodeId and
// ElementId belong to one generation and persistence promises nothing about
// them.

TEST_CASE("MeshingPersistence_ALoadedDocumentHasIntentAndNoMesh",
          "[meshing][io][persist][regenerate]") {
    TempDir temp;
    Tube part;
    MeshControlDefinition definition;
    definition.body = part.feature;
    definition.mesh.sizing.globalTargetSize = 5_mm;
    const MeshControlId control = addControl(part.document, "Mesh", definition);

    // Mesh it BEFORE saving, so a mesh exists in the process and could have
    // been written if the schema let it.
    meshing::Mesher before;
    REQUIRE(before.generate(part.document, part.regenerator, control).has_value());
    REQUIRE(before.currency(part.document, control) == meshing::MeshCurrency::Current);
    const std::size_t originalElements = before.mesh(control)->mesh().elementCount();

    const Document loaded = roundTrip(part.document, temp.path() / "regen.bcad");

    // A FRESH MESHER, which is what a fresh process has: no mesh for the
    // control, and the currency says so rather than claiming anything.
    meshing::Mesher after;
    const std::vector<MeshControlId> controls = meshing::meshControls(loaded);
    REQUIRE(controls.size() == 1U);
    CHECK(after.currency(loaded, controls.front()) == meshing::MeshCurrency::NoMesh);
    CHECK(after.mesh(controls.front()) == nullptr);

    // Now ask. The geometry has to be regenerated first -- the document holds
    // feature definitions, not bodies -- and then the mesh follows from the
    // loaded intent.
    features::Regenerator regenerator;
    Document working = roundTrip(part.document, temp.path() / "regen2.bcad");
    requireReport(regenerator, working);
    const std::vector<MeshControlId> workingControls = meshing::meshControls(working);
    REQUIRE(workingControls.size() == 1U);
    const Result<const meshing::VolumeMesh*> mesh =
        after.generate(working, regenerator, workingControls.front());
    INFO((mesh ? std::string{} : mesh.error().message));
    REQUIRE(mesh.has_value());
    CHECK(after.currency(working, workingControls.front()) == meshing::MeshCurrency::Current);

    // SEMANTICALLY THE SAME MESH, because the same intent met the same
    // geometry. Compared by element count, which is derived from the sizing
    // and could not match by accident if the intent had been lost.
    CHECK((*mesh)->mesh().elementCount() == originalElements);
}

TEST_CASE("MeshingPersistence_LocalRefinementStillRefinesTheSameFaceAfterLoad",
          "[meshing][io][persist][regenerate]") {
    // §61's fixture: a coarse global size with a fine local control on one
    // face. The point is that the refinement survives as INTENT and acts on
    // the same canonical face after a round trip -- the facet identities it
    // produces are free to differ and are not compared.
    TempDir temp;
    Tube part;
    const FaceName cap{part.feature, FaceSelector{.role = FaceRole::EndCap}};

    MeshControlDefinition coarse;
    coarse.body = part.feature;
    coarse.mesh.sizing.globalTargetSize = 6_mm;
    const MeshControlId plain = addControl(part.document, "Coarse", coarse);

    MeshControlDefinition refined = coarse;
    refined.mesh.sizing.local.push_back(LocalMeshSizing{.face = cap, .targetSize = 1.5_mm});
    const MeshControlId local = addControl(part.document, "Refined", refined);

    meshing::Mesher before;
    REQUIRE(before.generate(part.document, part.regenerator, plain).has_value());
    REQUIRE(before.generate(part.document, part.regenerator, local).has_value());
    const std::size_t plainElements = before.mesh(plain)->mesh().elementCount();
    const std::size_t localElements = before.mesh(local)->mesh().elementCount();
    // The local control must actually refine, or the comparison after the
    // load would be vacuous.
    REQUIRE(localElements > plainElements);

    Document loaded = roundTrip(part.document, temp.path() / "refine.bcad");
    features::Regenerator regenerator;
    requireReport(regenerator, loaded);

    const std::vector<MeshControlId> controls = meshing::meshControls(loaded);
    REQUIRE(controls.size() == 2U);
    // The refined one is the control that has a local sizing, found by its
    // canonical face rather than by position.
    std::optional<MeshControlId> refinedId;
    std::optional<MeshControlId> plainId;
    for (const MeshControlId id : controls) {
        const MeshControl* control = meshing::findMeshControl(loaded, id);
        REQUIRE(control != nullptr);
        if (control->localSizing(cap) != nullptr) {
            CHECK(control->localSizing(cap)->targetSize == 1.5_mm);
            refinedId = id;
        } else {
            plainId = id;
        }
    }
    REQUIRE(refinedId.has_value());
    REQUIRE(plainId.has_value());

    meshing::Mesher after;
    REQUIRE(after.generate(loaded, regenerator, *plainId).has_value());
    REQUIRE(after.generate(loaded, regenerator, *refinedId).has_value());
    // Same counts as before the save, and still refined relative to the plain
    // control: the refinement is acting on the same face.
    CHECK(after.mesh(*plainId)->mesh().elementCount() == plainElements);
    CHECK(after.mesh(*refinedId)->mesh().elementCount() == localElements);
    CHECK(after.mesh(*refinedId)->mesh().elementCount() >
          after.mesh(*plainId)->mesh().elementCount());
}

TEST_CASE("MeshingPersistence_ABoundarySetResolvesToCurrentFacetsAfterLoad",
          "[meshing][io][persist][regenerate]") {
    // §62: the set's canonical faces survive; the facets they resolve to are
    // derived from whatever mesh exists now, and are not expected to match
    // any earlier generation's identities.
    TempDir temp;
    Tube part;
    const FaceName cap{part.feature, FaceSelector{.role = FaceRole::EndCap}};
    const BoundarySetId setId = BoundarySetId::fromValue(6U);

    MeshControlDefinition definition;
    definition.body = part.feature;
    definition.mesh.sizing.globalTargetSize = 5_mm;
    definition.boundarySets.push_back(
        NamedBoundarySet{.id = setId, .name = "fixed_end", .faces = {cap}});
    (void)addControl(part.document, "Mesh", definition);

    Document loaded = roundTrip(part.document, temp.path() / "sets-regen.bcad");
    features::Regenerator regenerator;
    requireReport(regenerator, loaded);
    const MeshControl& control = onlyControl(loaded);

    // The intent came back with its identity, name and face.
    const NamedBoundarySet* set = control.boundarySet(setId);
    REQUIRE(set != nullptr);
    CHECK(set->id == setId);
    CHECK(set->name == "fixed_end");
    REQUIRE(set->faces.size() == 1U);
    CHECK(set->faces.front() == cap);

    // And it resolves against the mesh generated now.
    meshing::Mesher mesher;
    const std::vector<MeshControlId> controls = meshing::meshControls(loaded);
    REQUIRE(controls.size() == 1U);
    const Result<const meshing::VolumeMesh*> mesh =
        mesher.generate(loaded, regenerator, controls.front());
    INFO((mesh ? std::string{} : mesh.error().message));
    REQUIRE(mesh.has_value());
    const meshing::GeometryMeshMap* map = mesher.map(controls.front());
    REQUIRE(map != nullptr);

    const Result<meshing::ResolvedBoundarySet> resolved =
        meshing::resolveBoundarySet(*set, *map);
    INFO((resolved ? std::string{} : resolved.error().message));
    REQUIRE(resolved.has_value());
    CHECK(resolved->id == setId);
    CHECK(resolved->name == "fixed_end");
    CHECK(resolved->fullyResolved());
    // Facets exist for it. WHICH facets belongs to this generation, so the
    // count is reported rather than compared with a number from before the
    // save -- persistence promises the face, not the facets.
    CHECK_FALSE(resolved->mapping.facets.empty());
    WARN(std::format("boundary set resolved to {} facets of {} elements after load",
                     resolved->mapping.facets.size(), (*mesh)->mesh().elementCount()));
}

TEST_CASE("MeshingPersistence_QualityIsRecomputedAndNotRestored",
          "[meshing][io][persist][regenerate]") {
    // §96: the report is recomputed from the regenerated mesh. The POLICY
    // persists; the measurements do not, and the file was already shown to
    // contain no quality report at all.
    TempDir temp;
    Tube part;
    MeshControlDefinition definition;
    definition.body = part.feature;
    definition.mesh.sizing.globalTargetSize = 5_mm;
    definition.quality.limits.emplace(QualityMetric::TetRadiusRatio,
                                      QualityThreshold{.warning = 0.01, .failure = 0.001});
    (void)addControl(part.document, "Mesh", definition);

    Document loaded = roundTrip(part.document, temp.path() / "quality.bcad");
    features::Regenerator regenerator;
    requireReport(regenerator, loaded);
    const std::vector<MeshControlId> controls = meshing::meshControls(loaded);
    REQUIRE(controls.size() == 1U);

    // The policy survived.
    const MeshControl& control = onlyControl(loaded);
    REQUIRE(control.definition().quality.limits.contains(QualityMetric::TetRadiusRatio));
    CHECK(control.definition().quality.limits.at(QualityMetric::TetRadiusRatio).warning == 0.01);

    meshing::Mesher mesher;
    REQUIRE(mesher.generate(loaded, regenerator, controls.front()).has_value());
    const meshing::MeshQualityReport* report = mesher.quality(controls.front());
    REQUIRE(report != nullptr);
    // Measured now, under the loaded policy.
    CHECK(mesher.qualityDescribesCurrentPolicy(loaded, controls.front()));
    // A valid body meshes to structurally valid elements.
    CHECK(report->invalidElements == 0U);
}

// ---------------------------------------------------------------------------
// The command layer after a load
// ---------------------------------------------------------------------------

TEST_CASE("MeshingPersistence_CommandsUndoAndRedoExactlyAfterALoad",
          "[meshing][io][persist][commands]") {
    // §72 and §99. Persistence must restore intent in a form the command layer
    // fully understands -- the same IDs, the same references -- or an undo
    // after a load would not be exact.
    TempDir temp;
    Part part;
    const MeshControlId original = addControl(part.document, "Mesh", fullDefinition(part));
    Document loaded = roundTrip(part.document, temp.path() / "commands.bcad");

    const std::vector<MeshControlId> controls = meshing::meshControls(loaded);
    REQUIRE(controls.size() == 1U);
    // THE SAME MeshControlId, which is what makes a command written before the
    // save still name the right object after it.
    CHECK(controls.front() == original);

    CommandHistory history;
    const std::string loadedState = fingerprint(onlyControl(loaded));

    const Result<void> edit = history.execute(
        loaded, std::make_unique<meshing::SetGlobalMeshSizeCommand>(
                    controls.front(), std::optional<Length>{3_mm}));
    INFO((edit ? std::string{} : edit.error().message));
    REQUIRE(edit.has_value());
    CHECK(onlyControl(loaded).definition().mesh.sizing.globalTargetSize == 3_mm);

    REQUIRE(history.undo(loaded).has_value());
    CHECK(fingerprint(onlyControl(loaded)) == loadedState);
    REQUIRE(history.redo(loaded).has_value());
    CHECK(onlyControl(loaded).definition().mesh.sizing.globalTargetSize == 3_mm);

    // A local edit too, against a reference that came out of the file.
    const Result<void> local = history.execute(
        loaded, std::make_unique<meshing::EditLocalMeshSizingCommand>(controls.front(),
                                                                       part.top(), 0.5_mm));
    INFO((local ? std::string{} : local.error().message));
    REQUIRE(local.has_value());
    CHECK(onlyControl(loaded).localSizing(part.top())->targetSize == 0.5_mm);
    REQUIRE(history.undo(loaded).has_value());
    CHECK(onlyControl(loaded).localSizing(part.top())->targetSize == 1_mm);

    // And a removal, whose undo must restore the same face reference.
    const Result<void> remove = history.execute(
        loaded, std::make_unique<meshing::RemoveLocalMeshSizingCommand>(controls.front(),
                                                                         part.top()));
    REQUIRE(remove.has_value());
    CHECK(onlyControl(loaded).localSizing(part.top()) == nullptr);
    REQUIRE(history.undo(loaded).has_value());
    REQUIRE(onlyControl(loaded).localSizing(part.top()) != nullptr);
    CHECK(onlyControl(loaded).localSizing(part.top())->face == part.top());

    // Back to exactly what the file said.
    REQUIRE(history.undo(loaded).has_value());
    CHECK(fingerprint(onlyControl(loaded)) == loadedState);
}

TEST_CASE("MeshingPersistence_AControlCreatedAfterALoadCannotCollideWithALoadedId",
          "[meshing][io][persist][commands]") {
    // §70: the allocator is restored, so a new object does not take an ID the
    // file already used. `last_allocated_id` is persisted for exactly this and
    // the loader refuses a value below an ID in use -- verified here through
    // the meshing path rather than assumed from the header.
    TempDir temp;
    Part part;
    const MeshControlId first = addControl(part.document, "Mesh", fullDefinition(part));
    Document loaded = roundTrip(part.document, temp.path() / "allocator.bcad");

    CommandHistory history;
    MeshControlDefinition another;
    another.body = part.feature;
    another.mesh.sizing.globalTargetSize = 2_mm;
    auto create = std::make_unique<meshing::CreateMeshControlCommand>("Second", another);
    meshing::CreateMeshControlCommand* raw = create.get();
    const Result<void> executed = history.execute(loaded, std::move(create));
    INFO((executed ? std::string{} : executed.error().message));
    REQUIRE(executed.has_value());

    const MeshControlId second = raw->meshControlId();
    CHECK(second.isValid());
    CHECK_FALSE(second == first);
    // And it did not take the ID of ANY object the file restored.
    for (const DocumentObject& object : loaded.objects()) {
        if (object.id().value() != second.value()) {
            continue;
        }
        CHECK(meshing::findMeshControl(loaded, second) != nullptr);
    }
    CHECK(meshing::meshControls(loaded).size() == 2U);
}

// ---------------------------------------------------------------------------
// The hand-written reference file
// ---------------------------------------------------------------------------
//
// examples/models/meshed_plate.bcad is WRITTEN BY HAND, as plate.bcad is and
// for the same stated reason: it shows the format is readable and editable
// without BetterCAD, and it serves the CLI process tests. For this milestone
// it does more than that.
//
//   - It is the schema's permanent anchor. An incompatible change to the
//     persisted form of meshing intent breaks this test, deliberately.
//   - It is the backend-independence evidence that cannot be argued with: a
//     person wrote this file with no mesher present, and BetterCAD interprets
//     every field of it. Nothing in it names Netgen, because nothing has to.
//   - Loaded by `bettercad_cli` in a FRESH PROCESS by the process test
//     cli.open.mesh-control, which is what proves the restored intent carries
//     no in-memory identity: no pointer, no address, no per-process hash.

TEST_CASE("MeshingPersistence_TheHandWrittenReferenceFileLoadsAsWritten",
          "[meshing][io][persist][reference]") {
    const std::filesystem::path file =
        std::filesystem::path{BETTERCAD_EXAMPLE_MODELS_DIR} / "meshed_plate.bcad";
    REQUIRE(std::filesystem::exists(file));

    Result<Document> loaded = io::loadDocument(file);
    INFO((loaded ? std::string{} : loaded.error().message));
    REQUIRE(loaded.has_value());

    const MeshControl& control = onlyControl(*loaded);
    CHECK(control.name() == "PlateMesh");
    // The extrude the file names, as an ObjectId rather than a position.
    const ObjectId body = ObjectId::fromValue(6U);
    CHECK(control.definition().body == body);

    // Global sizing, exactly as written: 0.008 m, which is 8 mm.
    REQUIRE(control.definition().mesh.sizing.globalTargetSize.has_value());
    CHECK(*control.definition().mesh.sizing.globalTargetSize == 8_mm);
    CHECK(control.definition().mesh.surface.linearDeflection == Length::fromSi(0.0001));

    // Two local controls, one on the end cap and one on the side face the
    // file names by sketch entity 5.
    const FaceName cap{body, FaceSelector{.role = FaceRole::EndCap}};
    const FaceName side{body,
                        FaceSelector{.role = FaceRole::Side, .entity = EntityId::fromValue(5U)}};
    REQUIRE(control.localSizing(cap) != nullptr);
    CHECK(control.localSizing(cap)->targetSize == 2_mm);
    REQUIRE(control.localSizing(side) != nullptr);
    CHECK(control.localSizing(side)->targetSize == 4_mm);

    // The threshold policy.
    REQUIRE(control.definition().quality.limits.contains(QualityMetric::TetMinDihedralAngle));
    const QualityThreshold& limit =
        control.definition().quality.limits.at(QualityMetric::TetMinDihedralAngle);
    CHECK(limit.warning == 0.3);
    CHECK(limit.failure == 0.1);

    // The boundary set, with its identity and its face.
    const NamedBoundarySet* fixed = control.boundarySet(BoundarySetId::fromValue(1U));
    REQUIRE(fixed != nullptr);
    CHECK(fixed->name == "fixed_end");
    REQUIRE(fixed->faces.size() == 1U);
    CHECK(fixed->faces.front() == FaceName{body, FaceSelector{.role = FaceRole::StartCap}});
}

TEST_CASE("MeshingPersistence_TheReferenceFileRegeneratesAndMeshes",
          "[meshing][io][persist][reference]") {
    // END TO END from a hand-written file: load intent, regenerate geometry,
    // generate a mesh from the loaded intent, and resolve the loaded boundary
    // set against it. Nothing in this chain existed in memory before the load.
    Result<Document> loaded = io::loadDocument(
        std::filesystem::path{BETTERCAD_EXAMPLE_MODELS_DIR} / "meshed_plate.bcad");
    INFO((loaded ? std::string{} : loaded.error().message));
    REQUIRE(loaded.has_value());

    features::Regenerator regenerator;
    requireReport(regenerator, *loaded);

    const std::vector<MeshControlId> controls = meshing::meshControls(*loaded);
    REQUIRE(controls.size() == 1U);
    meshing::Mesher mesher;
    // No mesh until asked -- the file carried none and none was conjured.
    REQUIRE(mesher.currency(*loaded, controls.front()) == meshing::MeshCurrency::NoMesh);

    const Result<const meshing::VolumeMesh*> mesh =
        mesher.generate(*loaded, regenerator, controls.front());
    INFO((mesh ? std::string{} : mesh.error().message));
    REQUIRE(mesh.has_value());
    CHECK(mesher.currency(*loaded, controls.front()) == meshing::MeshCurrency::Current);
    CHECK((*mesh)->mesh().elementCount() > 0U);

    const meshing::MeshQualityReport* report = mesher.quality(controls.front());
    REQUIRE(report != nullptr);
    CHECK(report->invalidElements == 0U);

    const meshing::GeometryMeshMap* map = mesher.map(controls.front());
    REQUIRE(map != nullptr);
    const MeshControl& control = onlyControl(*loaded);
    const NamedBoundarySet* fixed = control.boundarySet(BoundarySetId::fromValue(1U));
    REQUIRE(fixed != nullptr);
    const Result<meshing::ResolvedBoundarySet> resolved =
        meshing::resolveBoundarySet(*fixed, *map);
    INFO((resolved ? std::string{} : resolved.error().message));
    REQUIRE(resolved.has_value());
    CHECK(resolved->fullyResolved());
    WARN(std::format("hand-written reference: {} nodes, {} elements, boundary set "
                     "'fixed_end' -> {} facets",
                     (*mesh)->mesh().nodeCount(), (*mesh)->mesh().elementCount(),
                     resolved->mapping.facets.size()));
}
