@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P17-SOLVE-001 -- Linear Static Solver. The exact invocation, recorded so
rem the run is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, nineteen in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and was not edited
rem (11855b8ff891093b021d1e0351761283d0eedd24).
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of over 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem NO PREDECESSOR PRODUCTION FILE WAS MODIFIED, so brief section 150's
rem requalification requirement has nothing to act on. `git status` over src
rem and include shows two NEW files plus src/structural/CMakeLists.txt, which
rem gained the Eigen PRIVATE link and the new source and nothing else.
rem
rem ONE PIECE OF SHARED TEST INFRASTRUCTURE DID CHANGE, and it is in the repeat
rem set for that reason: tests/architecture/CheckLayering.cmake gained rule 7,
rem which keeps Eigen out of every public header in the tree (ADR-039). It runs
rem over include/, src/, apps/ and examples/ in one pass, so a mistake in it
rem would mis-report any module -- which is why `architecture` is repeated and
rem why the rule ships with its own fixture self-test,
rem architecture.checker.eigen-public-header, holding BOTH a violation and a
rem permitted use so the expected count of one proves it fires on the right
rem one.
rem
rem The unit system gained nothing, so unit\.Unit and unit\.Quantity are NOT in
rem the set; no material or load code changed, so unit\.Material and unit\.Mass
rem are not either. Everything still runs unfiltered in all three presets,
rem which is where a change nobody predicted is caught.
rem
rem What IS in reach, and why:
rem
rem   unit\.Structural         this milestone's 25 (19 unit + 6 reference,
rem                            VERIFIED by counting StructuralSolve_ inside the
rem                            selection rather than by reading the filter --
rem                            P17-DOF-001 found a filter that covered 17 of
rem                            31 tests), plus P17-ASSEMBLY's 26, P17-BC's 32,
rem                            P17-LOAD's 23, P17-ELEM's, P17-MAT's,
rem                            P17-DATA's and P17-ARCH's. Every one of them is
rem                            CONSUMED here: the global K and F from
rem                            P17-ASSEMBLY, the constrained set from P17-BC,
rem                            the free numbering from P17-DOF, and through
rem                            them Ke from P17-ELEM and the loads from
rem                            P17-LOAD. A solve is the first milestone that
rem                            exercises the whole chain end to end
OLD_END
rem   unit\.MeshDofMap, unit\.ConstraintSet, unit\.FreeEquationMap
rem                            P17-DOF's. The global ROW SPACE is the free
rem                            numbering of the empty constraint set, so all
rem                            three are on the assembly's critical path: a
rem                            change to equationOf would move every row
rem   unit\.Tet4Element        P17-ELEM's 29. Every global entry is a sum of
rem                            Ke entries, so a change to the element
rem                            formulation changes every matrix this milestone
rem                            produces -- the most directly coupled
rem                            predecessor there is
rem   unit\.Mesh, unit\.Volume, unit\.Tet
rem                            P16's MAPPING contract, which is this module's
rem                            load-bearing dependency: every target is
rem                            resolved by boundaryFacetsOf and every node set
rem                            comes from boundaryNodesOf, whose sort-and-
rem                            unique is what this milestone deliberately does
rem                            NOT reimplement. Also matches P16-REFMOD-001's
rem                            reference cases, which all begin "Mesh"
rem   unit\.Siz                P16-SIZE's. The unit fixture and the RM-MESH-07
rem                            case both drive LOCAL sizing, and the large-mesh
rem                            fixture drives surface deflection to 0.025 mm
rem   unit\.Id                 the identity machinery
rem   architecture             containment and layering over the whole tree,
rem                            because a new public header went into an
rem                            existing module
OLD_END
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12)
rem   unit\.Analytic           the independent geometry toolkit's own tests
rem   refmod\.                 every reference-model process test
rem   gui\.                    the application links the structural library
rem
rem compile_fail is excluded from the REPEAT for the reason the previous seven
rem milestones recorded: each case is a real COMPILATION, so repeating one
rem measures the compiler's determinism and not BetterCAD's. All six new cases
rem still run UNFILTERED in all three presets, which is where a compile-fail
rem regression is caught.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Structural|unit\.MeshDofMap|unit\.ConstraintSet|unit\.FreeEquationMap|unit\.Tet4Element|unit\.Mesh|unit\.Volume|unit\.Tet|unit\.Siz|unit\.Id|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
