@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P17-ARCH-001 -- Structural FEA Architecture. The exact invocation,
rem recorded so the run is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem P16 milestone since used, eleven in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and is meant to be run
rem whenever it is edited, which it was not. It is NOT P15-QUAL-001's file
rem (b44335cc): three %REPEAT% uses became !REPEAT! during P16.
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of nearly 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE BLAST RADIUS OF THIS MILESTONE, and it is wider than its diff.
rem
rem One new module of two files, and one change to a TEST SCRIPT that reaches
rem every module in the repository: tests/architecture/CheckLayering.cmake had
rem its layer table respaced from consecutive integers to tens, and gained a
rem sixth rule. Relative order is unchanged, so no dependency direction moved
rem -- but the script is the thing that decides whether EVERY #include in
rem include/, src/, apps/ and examples/ is legal, so the repeat set must
rem include it and the fixtures that prove each rule still fires.
rem
rem   architecture             the respaced table and all six rules, over 447
rem                            files, plus the 13 checker self-tests: one tree
rem                            per violation kind and a valid tree. Four are
rem                            this milestone's: structural -> io, the
rem                            meshing -> structural CYCLE, a backend header in
rem                            src/structural/, and src/ -> apps/
rem   unit\.StructuralInput    the new input boundary, 10 cases
rem   unit\.Mesh               every meshing and mesh-renderer test, AND
rem                            P16-REFMOD-001's 28 reference cases, which all
rem                            begin "Mesh". The boundary consumes Mesher,
rem                            VolumeMesh, GeometryMeshMap and
rem                            MeshQualityReport, so an ordering assumption in
rem                            any of them would surface here
rem   unit\.Volume             the volume mesh contract
rem   unit\.Siz                sizing -- the generation-failure case drives an
rem                            unresolvable local control through resolveSizing
rem   unit\.Netgen             the backend
rem   unit\.Surface            the boundary the backend is given
rem   unit\.Tet                element validation
rem   unit\.Material           P15's material resolution, which the boundary
rem                            consumes through requireEffectiveMaterial and
rem                            requireLinearElasticConstants
rem   unit\.Mass               the other consumer of the same material
rem                            contract, included so a change in that contract
rem                            cannot be seen from one side only
rem   unit\.Analytic           the independent geometry toolkit's own tests
rem   refmod\.                 every reference-model process test
rem   gui\.                    the application links the library whose layer
rem                            table moved
rem
rem compile_fail is excluded, and the reason is specific rather than
rem convenience: this milestone adds no compile-fail case, `structural` has no
rem compile_fail group, and the respace cannot reach them -- those tests assert
rem that a C++ conversion fails to COMPILE, which no layer number affects. Each
rem is a real compilation, so five rounds of roughly two hundred would cost
rem about two hours and report nothing about this milestone. They still run
rem UNFILTERED in all three presets, which is where a compile-fail regression
rem would be caught.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has already
rem passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.StructuralInput|unit\.Mesh|unit\.Volume|unit\.Siz|unit\.Netgen|unit\.Surface|unit\.Tet|unit\.Material|unit\.Mass|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
