@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem
rem EVERY LINE OF THIS FILE BEGINS WITH rem, set, call, echo, setlocal,
rem endlocal OR @echo, AND THAT IS CHECKED BEFORE THE RUN. P17-ASSEMBLY-001's
rem and P17-SOLVE-001's copies each carried bare OLD_END lines -- leaked
rem heredoc terminators -- which cmd.exe reported into their .err files. They
rem were corrected by P17-POST-001 and the check is now part of the freeze.
rem ---------------------------------------------------------------------
rem
rem P17-REACTION-001 -- Reaction Forces / Equilibrium. The exact invocation,
rem recorded so the run is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, TWENTY-ONE in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and was not edited
rem (11855b8ff891093b021d1e0351761283d0eedd24).
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of over 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem WHAT CHANGED, AND WHAT IS OWED BY IT.
rem
rem   NEW          include/bettercad/structural/StructuralReaction.hpp
rem                src/structural/StructuralReaction.cpp
rem                tests/structural/StructuralReactionTests.cpp
rem                tests/reference/StructuralReactionReferenceTests.cpp
rem                tests/compile_fail/StructuralReactionMisuse.cpp
rem   MODIFIED     src/structural/CMakeLists.txt     the new source, nothing
rem                                                  else
rem                tests/CMakeLists.txt              two registrations
rem                tests/compile_fail/CMakeLists.txt one group, six cases
rem
rem   MODIFIED, AND THIS ONE IS QUALIFIED P17-BC-001 CODE:
rem                include/bettercad/structural/StructuralConstraints.hpp
rem                src/structural/StructuralConstraints.cpp
rem
rem                `RestraintResolution` gained its resolved DofIndex list
rem                (ADR-041). Per-restraint reaction inspection is a REQUIRED
rem                checklist item and counts cannot attribute a reaction; the
rem                only alternative was to re-resolve each restraint's target
rem                after the solve and ASSUME the geometry mapping reproduced
rem                the same set, which is how a source mismatch hides.
rem
rem                The change is ADDITIVE and keeps a value already computed:
rem                that loop already called numbering.indexOf for every degree
rem                of freedom it resolved, verified the answer, and discarded
rem                the index. `degreesOfFreedom` is now `constrained.size()`,
rem                which equals the previous `nodes * components.count()`
rem                because a restraint's nodes are unique and its components
rem                are a mask.
rem
rem                REQUALIFICATION OWED AND PAID: unit\.Structural is in the
rem                repeat set, so P17-BC-001's 32 tests run 5x in two presets
rem                and unfiltered in all three, as do P17-DOF's, P17-LOAD's,
rem                P17-ASSEMBLY's, P17-SOLVE's and P17-POST's. P17-BC's own
rem                suite was also run before the freeze and passed 32/32.
rem
rem NO OTHER PREDECESSOR PRODUCTION FILE WAS MODIFIED. In particular
rem StructuralSolve.cpp is untouched: this milestone CONSUMES
rem SolvedSystem::fullResidual(), which that header retained for it by name,
rem and computes no second residual.
rem
rem NO SHARED TEST INFRASTRUCTURE CHANGED. tests/architecture/CheckLayering.cmake
rem is byte-identical to P17-POST-001's; architecture is in the repeat set
rem because a new public header went into an existing module.
rem
rem What IS in reach, and why:
rem
rem   unit\.Structural         this milestone's 21 (17 unit + 4 reference),
rem                            VERIFIED by counting StructuralReaction_ inside
rem                            the selection rather than by reading the filter
rem                            -- P17-DOF-001 found a filter that covered 17
rem                            of 31 tests. The 6 compile-failure cases are
rem                            NOT in this filter; they run unfiltered.
rem
rem                            CORRECTED AFTER THE RUN: this line first said
rem                            "27 (21 unit + 6 reference)", which was wrong
rem                            arithmetic and wrong attribution -- 27 is the
rem                            total INCLUDING compile_fail, and the split is
rem                            17/4. The filter itself is `unit\.Structural`
rem                            and selects whatever exists, so the run was not
rem                            affected: it selected 748 tests and the counts
rem                            above were read back out of its own logs. The
rem                            file could not be edited while it ran, because
rem                            cmd.exe reads a batch file by byte offset.
rem
rem                            Plus P17-POST's 41, P17-SOLVE's
rem                            25, P17-ASSEMBLY's 26, P17-BC's 32, P17-LOAD's
rem                            23, P17-ELEM's 29, and P17-MAT's, P17-DATA's
rem                            and P17-ARCH's. P17-BC's are in reach TWICE
rem                            over: as a consumer and as the milestone whose
rem                            shared code changed.
rem   unit\.MeshDofMap, unit\.ConstraintSet, unit\.FreeEquationMap
rem                            P17-DOF's. Every reaction is located by
rem                            dofAt/indicesOf and every constrained degree of
rem                            freedom comes from the ConstraintSet, so a
rem                            change to either would misattribute reactions.
rem   unit\.Tet4Element        P17-ELEM's. K comes from Ke, and the reaction
rem                            IS a row of K u - F.
rem   unit\.Mesh, unit\.Volume, unit\.Tet
rem                            P16's enumeration and node positions. Every
rem                            moment is (x - O) x F, so a change to node
rem                            ordering or coordinates reaches every moment.
rem   unit\.Siz                P16-SIZE's. The remesh test drives a global
rem                            target change and the large-mesh reference case
rem                            drives surface deflection to 0.025 mm.
rem   unit\.Id                 the identity machinery.
rem   architecture             containment and layering over the whole tree.
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12).
rem   unit\.Analytic           the independent geometry toolkit's own tests.
rem   refmod\.                 every reference-model process test.
rem   gui\.                    the application links the structural library.
rem
rem The unit system gained nothing, so unit\.Unit and unit\.Quantity are NOT
rem in the set. unit\.Material and unit\.Mass are not either: no material code
rem changed. Everything still runs unfiltered in all three presets, which is
rem where a change nobody predicted is caught.
rem
rem compile_fail is excluded from the REPEAT for the reason the previous nine
rem milestones recorded: each case is a real COMPILATION, so repeating one
rem measures the compiler's determinism and not BetterCAD's. All six new cases
rem still run UNFILTERED in all three presets.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Structural|unit\.MeshDofMap|unit\.ConstraintSet|unit\.FreeEquationMap|unit\.Tet4Element|unit\.Mesh|unit\.Volume|unit\.Tet|unit\.Siz|unit\.Id|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
