@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P16-REFMOD-001 qualification: the exact invocation, recorded so the run is
rem reproducible rather than described.
rem
rem qualify.cmd is carried UNCHANGED from P15-QUAL-001, byte for byte
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b);
rem verify-harness.cmd beside it is its regression and is meant to be run
rem whenever it is edited, which it was not.
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of nearly 600 template-heavy
rem translation units exhausted the commit charge -- "cc1plus.exe: out of
rem memory allocating 4198399 bytes", at object 286 of 592. ONE resource
rem failure became FIVE failed stages there. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE REPEAT FILTER IS THE BLAST RADIUS, and this milestone's is wider than
rem its subject, because it touches two things that are shared.
rem
rem ONE PRODUCTION FILE CHANGED: ResolvedSizing::unresolvedCount() moved from
rem src/meshing/MeshSizing.cpp into the header, inline. It is a public API
rem method of a NON-EXPORTED data struct, so defined out of line it was not
rem exported and no caller in another DLL could link against it -- which the
rem pre-freeze debug-shared-ext build found when this suite became its first
rem such caller. The change has no behaviour, and the determinism set is what
rem proves that rather than asserting it: every meshing test, the whole volume
rem mesh contract, the backend, the surface layer and the sizing module itself.
rem
rem AND THE REFERENCE-MODEL LIBRARY CHANGED: examples/reference_models gains
rem three sources and a PUBLIC link to BetterCAD::meshing, main.cpp gains a
rem --meshes loop, and tests/reference/Analytic.hpp gains a section. Every
rem reference suite in the repository is built from that library and that
rem header -- the twelve parts, the eight assemblies, the seven drawings and
rem the eight material models -- so all four are in the set. They are the
rem expensive half of it, and excluding them because they are slow would be
rem excluding exactly the tests a shared-library change could disturb.
rem
rem So the determinism set is:
rem
rem   unit\.Mesh              every meshing and mesh-renderer test, AND this
rem                           milestone's own 28 cases, which all begin "Mesh"
rem   unit\.Siz               the sizing module, whose header changed
rem   unit\.Volume            the volume mesh contract
rem   unit\.Netgen            the backend
rem   unit\.Surface           the boundary the backend is given
rem   unit\.Tet               element validation
rem   unit\.ReferenceModel    the twelve mechanical parts (P11/P12)
rem   unit\.AssemblyReference the eight assemblies (P13)
rem   unit\.DrawingReference  the seven drawings (P14)
rem   unit\.MaterialReference the eight material models (P15)
rem   unit\.Analytic          the independent geometry toolkit's own tests
rem   refmod\.                EVERY reference-model process test, because they
rem                           all run the same runner executable
rem   cli\.                   every cli test: the mesh commands sit on the
rem                           sizing module, and cli.validate.reference.* and
rem                           cli.assembly.* read what the runner writes
rem   gui\.                   the application links the same meshing module
rem   architecture            containment, with a new examples-to-module
rem                           dependency
rem
rem Measured: 692 tests, 327 s per pass in debug-ext, so five passes in each of
rem two presets is about 55 minutes of the run.
rem
rem compile_fail is excluded: this milestone adds no compile-fail case, and
rem nothing in examples/reference_models/ or tests/reference/ is included by
rem one. Each of those cases is a real compilation, so five rounds of roughly
rem two hundred would cost about two hours and report nothing about the
rem reference models. P16-CMD-001 included them because it added thirteen.
rem
rem It is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%: a %VAR%
rem holding | ( or ) is substituted when the for-block is PARSED and closes the
rem block early, killing the run after every preset has already passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=unit\.Mesh|unit\.Siz|unit\.Volume|unit\.Netgen|unit\.Surface|unit\.Tet|unit\.ReferenceModel|unit\.AssemblyReference|unit\.DrawingReference|unit\.MaterialReference|unit\.Analytic|refmod\.|cli\.|gui\.|architecture"
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
