@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P17-POST-001 -- Displacement / Strain / Stress Recovery. The exact
rem invocation, recorded so the run is reproducible rather than described.
rem
rem EVERY LINE OF THIS COMMENT BLOCK BEGINS WITH rem, AND THAT IS CHECKED.
rem P17-ASSEMBLY-001's and P17-SOLVE-001's copies of this file each carry one
rem or two bare OLD_END lines -- leaked heredoc terminators from the session
rem that wrote them -- and cmd.exe duly reported "'OLD_END' is not recognized
rem as an internal or external command" into run-qualification.err. Neither
rem run was affected: an unrecognized command prints to stderr and cmd.exe
rem carries on, and every stage still recorded exit 0. But a file that calls
rem itself "the exact invocation" should not contain lines that are not part
rem of it, so this one was written in one pass and grepped for any line not
rem starting with rem, set, call, echo, setlocal, endlocal or @echo.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, TWENTY in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and was not edited
rem (11855b8ff891093b021d1e0351761283d0eedd24).
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of over 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem WHAT CHANGED, AND WHAT IS OWED BY IT.
rem
rem   NEW          include/bettercad/structural/StructuralPost.hpp
rem                src/structural/StructuralPost.cpp
rem                tests/structural/StructuralPostTests.cpp
rem                tests/reference/StructuralPostReferenceTests.cpp
rem                tests/compile_fail/StructuralPostMisuse.cpp
rem   MODIFIED     src/structural/CMakeLists.txt   the new source, and nothing
rem                                                else -- Eigen was already a
rem                                                PRIVATE link (ADR-039)
rem                tests/CMakeLists.txt            two registrations
rem                tests/compile_fail/CMakeLists.txt  one group, six cases
rem                src/structural/StructuralSolve.cpp  A COMMENT ONLY. It said
rem                                                "EIGEN IS USED HERE AND
rem                                                NOWHERE ELSE IN THIS
rem                                                MODULE", which this
rem                                                milestone made false by
rem                                                admitting a second Eigen
rem                                                consumer. Leaving a false
rem                                                statement in a qualified
rem                                                header is worse than
rem                                                touching it; the executable
rem                                                is unchanged, and
rem                                                unit\.Structural is in the
rem                                                repeat set regardless.
rem
rem NO OTHER PREDECESSOR PRODUCTION FILE WAS MODIFIED, so brief section 154's
rem requalification requirement has nothing further to act on. In particular
rem P17-ELEM-001's Tet4Element.cpp is untouched: this milestone CONSUMES
rem strainFrom and stressFrom, which that header made public for it by name,
rem and reimplements neither.
rem
rem NO SHARED TEST INFRASTRUCTURE CHANGED. tests/architecture/CheckLayering.cmake
rem is byte-identical to P17-SOLVE-001's: rule 7 already keeps Eigen out of
rem every public header, and StructuralPost.hpp is the first new public header
rem since it was written, so the rule is EXERCISED rather than extended.
rem architecture is in the repeat set for exactly that reason.
rem
rem What IS in reach, and why:
rem
rem   unit\.Structural         this milestone's 41 (35 unit + 6 reference,
rem                            VERIFIED by counting StructuralPost_ inside the
rem                            selection rather than by reading the filter --
rem                            P17-DOF-001 found a filter that covered 17 of
rem                            31 tests), plus P17-SOLVE's 25, P17-ASSEMBLY's
rem                            26, P17-BC's 32, P17-LOAD's 23, P17-ELEM's 29,
rem                            P17-MAT's, P17-DATA's and P17-ARCH's. Recovery
rem                            is the first milestone that consumes the WHOLE
rem                            chain and then reads its answer back.
rem   unit\.Tet4Element        P17-ELEM's 29, and the most directly coupled
rem                            predecessor there is: every strain this
rem                            milestone produces is strainFrom and every
rem                            stress is stressFrom, so a change to either
rem                            changes every number here.
rem   unit\.MeshDofMap, unit\.ConstraintSet, unit\.FreeEquationMap
rem                            P17-DOF's. The twelve local indices come from
rem                            elementDegreesOfFreedom, which goes through
rem                            indicesOf, so a change to the numbering would
rem                            gather the wrong displacements.
rem   unit\.Mesh, unit\.Volume, unit\.Tet
rem                            P16's enumeration contract, which is this
rem                            module's load-bearing dependency: the result
rem                            ORDER is the mesh's ascending NodeId and
rem                            ElementId order, and nothing here sorts.
rem   unit\.Siz                P16-SIZE's. The remesh test drives a global
rem                            target change and the large-mesh reference case
rem                            drives surface deflection to 0.025 mm.
rem   unit\.Id                 the identity machinery.
rem   architecture             containment and layering over the whole tree,
rem                            because a new public header went into an
rem                            existing module -- and rule 7 must still refuse
rem                            Eigen in it.
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12).
rem   unit\.Analytic           the independent geometry toolkit's own tests.
rem   refmod\.                 every reference-model process test.
rem   gui\.                    the application links the structural library.
rem
rem The unit system gained nothing, so unit\.Unit and unit\.Quantity are NOT
rem in the set; no material or load code changed, so unit\.Material and
rem unit\.Mass are not either. Everything still runs unfiltered in all three
rem presets, which is where a change nobody predicted is caught.
rem
rem compile_fail is excluded from the REPEAT for the reason the previous eight
rem milestones recorded: each case is a real COMPILATION, so repeating one
rem measures the compiler's determinism and not BetterCAD's. All six new cases
rem still run UNFILTERED in all three presets, which is where a compile-fail
rem regression is caught.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Structural|unit\.MeshDofMap|unit\.ConstraintSet|unit\.FreeEquationMap|unit\.Tet4Element|unit\.Mesh|unit\.Volume|unit\.Tet|unit\.Siz|unit\.Id|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
