// P16-CMD-001: meshing commands, undo and redo.
//
// WHAT "EXACT" MEANS HERE, and it is the reason for the fingerprint below.
// Undo is not "the numbers look the same": it is that the canonical meshing
// intent after an undo equals the intent before the command, field for field,
// including the body it names, every local control's face reference and size,
// every boundary set's identity, name and selection, and the threshold policy.
// A fingerprint makes that one comparison instead of twenty, and makes a
// multi-step sequence checkable as a sequence.
//
// AND WHAT IS NEVER IN THE HISTORY: no nodes, no elements, no connectivity, no
// facet identities, no quality report, no mapping, no backend handle. The mesh
// an undo "restores" is not restored at all -- it is recomputed from the intent
// on the next request, which is what ADR-030 requires and what makes a history
// step cost a few bytes rather than a few megabytes.

#include "TestHelpers.hpp"
#include "features/FeatureTestSupport.hpp"

#include <bettercad/core/Units.hpp>
#include <bettercad/core/document/Command.hpp>
#include <bettercad/core/document/Document.hpp>
#include <bettercad/core/units/Literals.hpp>
#include <bettercad/features/ExtrudeFeature.hpp>
#include <bettercad/features/HoleFeature.hpp>
#include <bettercad/features/Regenerator.hpp>
#include <bettercad/meshing/MeshControl.hpp>
#include <bettercad/meshing/Mesher.hpp>
#include <bettercad/meshing/MeshingCommands.hpp>
#include <bettercad/sketch/Sketch.hpp>

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_string.hpp>

#include <algorithm>
#include <array>
#include <format>
#include <limits>
#include <memory>
#include <optional>
#include <string>
#include <utility>
#include <vector>

using namespace bettercad;
using namespace bettercad::literals;
using namespace bettercad::test;
using Catch::Matchers::ContainsSubstring;
using meshing::AddBoundarySetCommand;
using meshing::AddLocalMeshSizingCommand;
using meshing::CreateMeshControlCommand;
using meshing::describesTheModel;
using meshing::LocalMeshSizing;
using meshing::DeleteMeshControlCommand;
using meshing::EditBoundarySetCommand;
using meshing::EditLocalMeshSizingCommand;
using meshing::GeometryMeshMap;
using meshing::MeshControl;
using meshing::MeshControlDefinition;
using meshing::MeshCurrency;
using meshing::Mesher;
using meshing::NamedBoundarySet;
using meshing::QualityMetric;
using meshing::QualityThreshold;
using meshing::RemoveBoundarySetCommand;
using meshing::RemoveLocalMeshSizingCommand;
using meshing::SetGlobalMeshSizeCommand;
using meshing::SetMeshControlDefinitionCommand;
using meshing::VolumeMesh;

namespace {

struct Part {
    Document document{"Part"};
    features::Regenerator regenerator;
    ObjectId feature{};
    std::array<EntityId, 4> lines{};

    Part() {
        auto sketch = std::make_unique<sketch::Sketch>("Profile", Frame3D::xy());
        lines = addRectangle(*sketch, 0_mm, 0_mm, 30_mm, 20_mm);
        const ObjectId profile = require(document.addObject(std::move(sketch)));
        auto extrude = features::ExtrudeFeature::create(
            "Solid", {.profile = SketchId::fromValue(profile.value()), .depth = 10_mm});
        REQUIRE(extrude.has_value());
        feature = require(document.addObject(std::move(*extrude)));
        requireReport(regenerator, document);
    }

    [[nodiscard]] FaceName top() const {
        return FaceName{feature, FaceSelector{.role = FaceRole::EndCap}};
    }
    [[nodiscard]] FaceName bottom() const {
        return FaceName{feature, FaceSelector{.role = FaceRole::StartCap}};
    }
    [[nodiscard]] FaceName side(std::size_t which) const {
        return FaceName{feature, FaceSelector{.role = FaceRole::Side, .entity = lines[which]}};
    }
    [[nodiscard]] MeshControlDefinition definition() const {
        return MeshControlDefinition{.body = feature};
    }

    void setDepth(Length depth) {
        REQUIRE(document
                    .modifyObject<features::ExtrudeFeature>(
                        feature,
                        [depth](features::ExtrudeFeature& extrude) -> Result<bool> {
                            auto definition = extrude.definition();
                            definition.depth = depth;
                            return extrude.setDefinition(definition).has_value();
                        })
                    .has_value());
        requireReport(regenerator, document);
    }

    /// Re-profiles the extrude onto a CIRCLE, and returns the circle's entity.
    ///
    /// A topology change that keeps the feature's own ObjectId and leaves the
    /// `Side` role meaningful, while destroying the four line entities the
    /// rectangle's side faces were named by: a cylinder has one side face,
    /// generated by the circle.
    ///
    /// A CIRCLE AND NOT ANOTHER RECTANGLE, and the reason is a measurement.
    /// `EntityId` is allocated PER SKETCH, so a replacement rectangle's lines
    /// come out as the same entity numbers as the original's -- the first
    /// version of this fixture re-profiled onto a second rectangle and the
    /// control's `entity:7` resolved against the NEW sketch's seventh entity.
    /// That would have made this test assert a rebind while claiming to
    /// forbid one. See ADVERSARIAL_REVIEW.md, finding A5.
    [[nodiscard]] EntityId setProfileToCircle() {
        auto replacement = std::make_unique<sketch::Sketch>("Round", Frame3D::xy());
        const EntityId circle =
            require(replacement->addCircle(Point2D{10_mm, 10_mm}, 8_mm));
        const ObjectId profile = require(document.addObject(std::move(replacement)));
        REQUIRE(document
                    .modifyObject<features::ExtrudeFeature>(
                        feature,
                        [profile](features::ExtrudeFeature& extrude) -> Result<bool> {
                            auto definition = extrude.definition();
                            definition.profile = SketchId::fromValue(profile.value());
                            return extrude.setDefinition(definition).has_value();
                        })
                    .has_value());
        requireReport(regenerator, document);
        return circle;
    }
};

template <typename CommandType, typename... Args>
CommandType* run(CommandHistory& history, Document& document, Args&&... args) {
    auto command = std::make_unique<CommandType>(std::forward<Args>(args)...);
    CommandType* raw = command.get();
    const Result<void> result = history.execute(document, std::move(command));
    INFO((result ? std::string{} : result.error().message));
    REQUIRE(result.has_value());
    return raw;
}

template <typename CommandType, typename... Args>
[[nodiscard]] Error runExpectingFailure(CommandHistory& history, Document& document,
                                        Args&&... args) {
    auto command = std::make_unique<CommandType>(std::forward<Args>(args)...);
    const Result<void> result = history.execute(document, std::move(command));
    REQUIRE_FALSE(result.has_value());
    return result.error();
}

void requireUndo(CommandHistory& history, Document& document) {
    const Result<void> result = history.undo(document);
    INFO((result ? std::string{} : result.error().message));
    REQUIRE(result.has_value());
}

void requireRedo(CommandHistory& history, Document& document) {
    const Result<void> result = history.redo(document);
    INFO((result ? std::string{} : result.error().message));
    REQUIRE(result.has_value());
}

[[nodiscard]] const MeshControlDefinition& definitionOf(const Document& document,
                                                        MeshControlId control) {
    const MeshControl* found = meshing::findMeshControl(document, control);
    REQUIRE(found != nullptr);
    return found->definition();
}

/// Every field of a face reference, because a fingerprint that skipped one
/// could not detect an undo that lost it.
///
/// `FaceSelector`'s entity, path edge, sketch and chamfer-edge are all
/// OPTIONAL -- an end cap names no entity, a side face does -- so an absent
/// one is rendered as a distinct token rather than unwrapped. Unwrapping it
/// was the first version of this helper, and it threw on the first end-cap
/// control it saw.
[[nodiscard]] std::string describe(const FaceName& name) {
    const auto id = [](const auto& optional) {
        return optional.has_value() ? std::format("{}", optional->value()) : std::string{"-"};
    };
    std::string text = std::format("{},{},{},{},{},{}", name.feature.value(),
                                   static_cast<int>(name.face.role), id(name.face.entity),
                                   id(name.face.along), id(name.face.alongSketch),
                                   id(name.face.edge));
    for (const FaceCopy& copy : name.face.copies) {
        text += std::format(",copy({},{})", copy.feature.value(), copy.instance);
    }
    return text;
}

/// A deterministic rendering of the CANONICAL MESHING INTENT, and of nothing
/// else.
///
/// It reads only what a command may carry: the body, the discretisation and
/// sizing, the threshold policy and the boundary intent. There is deliberately
/// no mesh in it -- no node count, no element count, no quality figure -- so a
/// fingerprint that matched after an undo could not be matching because a
/// cached mesh happened to be the same.
///
/// Enumerated through the control's ordered accessors, because the stored
/// order of local controls carries no meaning (P16-SIZE-001) and a fingerprint
/// that depended on it would change when nothing semantic had.
[[nodiscard]] std::string fingerprint(const MeshControl& control) {
    const MeshControlDefinition& definition = control.definition();
    std::string text = std::format("body={}", definition.body.value());
    text += std::format("|global={}",
                        definition.mesh.sizing.globalTargetSize.has_value()
                            ? std::format("{:.12g}", definition.mesh.sizing.globalTargetSize->si())
                            : std::string{"default"});
    text += std::format("|deflection={:.12g}/{:.12g}",
                        definition.mesh.surface.linearDeflection.si(),
                        definition.mesh.surface.angularDeflection.si());
    for (const LocalMeshSizing& local : control.orderedLocalSizing()) {
        text += std::format("|local[{}]={:.12g}", describe(local.face), local.targetSize.si());
    }
    for (const NamedBoundarySet& set : control.orderedBoundarySets()) {
        text += std::format("|set[{}:{}]=", set.id.value(), set.name);
        for (const FaceName& face : set.faces) {
            text += std::format("({})", describe(face));
        }
    }
    for (const auto& [metric, threshold] : definition.quality.limits) {
        text += std::format("|limit[{}]={:.12g}/{:.12g}", static_cast<int>(metric),
                            threshold.warning.value_or(0.0), threshold.failure.value_or(0.0));
    }
    return text;
}

[[nodiscard]] std::string fingerprintOf(const Document& document, MeshControlId control) {
    const MeshControl* found = meshing::findMeshControl(document, control);
    REQUIRE(found != nullptr);
    return fingerprint(*found);
}

/// A cylinder, r 6 x h 20 mm.
///
/// THE FIXTURE THAT CAN SHOW SIZING AT ALL, and P16-SIZE-001 established it
/// for the same reason: a volume element cannot be smaller than the boundary
/// triangles it must conform to, and OCCT triangulates a PLANAR face with two
/// triangles whatever the deflection. The block above saturates at 24
/// tetrahedra -- 10 mm, 3 mm and 1.5 mm all give 24 -- so it cannot
/// demonstrate a mesh growing while a history step does not. A curved wall
/// subdivides with the deflection, so a cylinder can.
struct Tube {
    Document document{"Tube"};
    features::Regenerator regenerator;
    ObjectId feature{};

    Tube() {
        auto sketch = std::make_unique<sketch::Sketch>("Profile", Frame3D::xy());
        REQUIRE(sketch->addCircle(Point2D{0_mm, 0_mm}, 6_mm).has_value());
        const ObjectId profile = require(document.addObject(std::move(sketch)));
        auto extrude = features::ExtrudeFeature::create(
            "Solid", {.profile = SketchId::fromValue(profile.value()), .depth = 20_mm});
        REQUIRE(extrude.has_value());
        feature = require(document.addObject(std::move(*extrude)));
        requireReport(regenerator, document);
    }

    [[nodiscard]] FaceName top() const {
        return FaceName{feature, FaceSelector{.role = FaceRole::EndCap}};
    }
    [[nodiscard]] FaceName bottom() const {
        return FaceName{feature, FaceSelector{.role = FaceRole::StartCap}};
    }
    [[nodiscard]] MeshControlDefinition definition() const {
        return MeshControlDefinition{.body = feature};
    }
};

/// A control with a global size, so a sequence has something to restore.
template <typename Fixture>
[[nodiscard]] MeshControlId makeControl(Fixture& part, CommandHistory& history) {
    MeshControlDefinition definition = part.definition();
    definition.mesh.sizing.globalTargetSize = 10_mm;
    CreateMeshControlCommand* create =
        run<CreateMeshControlCommand>(history, part.document, "Mesh", definition);
    const MeshControlId control = create->meshControlId();
    REQUIRE(control.isValid());
    return control;
}

} // namespace

// ---------------------------------------------------------------------------
// Create and delete
// ---------------------------------------------------------------------------

TEST_CASE("MeshingCommand_CreateExecutesUndoesAndRedoesWithTheSameIdentity",
          "[meshing][meshcmd]") {
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    const std::string s1 = fingerprintOf(part.document, control);
    CHECK(meshing::meshControls(part.document).size() == 1U);

    requireUndo(history, part.document);
    CHECK(meshing::findMeshControl(part.document, control) == nullptr);
    CHECK(meshing::meshControls(part.document).empty());

    requireRedo(history, part.document);
    // THE SAME MeshControlId. A redo that minted a new one would leave every
    // reference to the original -- a held mesh, a later command -- dangling.
    REQUIRE(meshing::findMeshControl(part.document, control) != nullptr);
    CHECK(fingerprintOf(part.document, control) == s1);
}

TEST_CASE("MeshingCommand_DeleteRestoresTheWholeControlOnUndo", "[meshing][meshcmd]") {
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 2_mm);
    const std::string before = fingerprintOf(part.document, control);

    (void)run<DeleteMeshControlCommand>(history, part.document, control);
    CHECK(meshing::findMeshControl(part.document, control) == nullptr);

    requireUndo(history, part.document);
    REQUIRE(meshing::findMeshControl(part.document, control) != nullptr);
    CHECK(fingerprintOf(part.document, control) == before);
    CHECK(meshing::findMeshControl(part.document, control)->name() == "Mesh");
}

TEST_CASE("MeshingCommand_RefusesAnIdThatIsNotAMeshControl", "[meshing][meshcmd][validation]") {
    // A sketch's ID handed to a meshing command must not silently work.
    Part part;
    CommandHistory history;
    const MeshControlId notAControl = MeshControlId::fromValue(part.feature.value());
    const std::size_t depth = history.undoCount();

    CHECK(runExpectingFailure<DeleteMeshControlCommand>(history, part.document, notAControl).code ==
          ErrorCode::NotFound);
    CHECK(runExpectingFailure<SetGlobalMeshSizeCommand>(history, part.document, notAControl,
                                                        std::optional<Length>{5_mm})
              .code == ErrorCode::NotFound);
    CHECK(history.undoCount() == depth);
}

// ---------------------------------------------------------------------------
// Global sizing
// ---------------------------------------------------------------------------

TEST_CASE("MeshingCommand_GlobalSizeIsExactThroughUndoAndRedo", "[meshing][meshcmd][global]") {
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    CHECK(definitionOf(part.document, control).mesh.sizing.globalTargetSize == 10_mm);

    SetGlobalMeshSizeCommand* edit = run<SetGlobalMeshSizeCommand>(
        history, part.document, control, std::optional<Length>{5_mm});
    CHECK(edit->changedAnything());
    CHECK(definitionOf(part.document, control).mesh.sizing.globalTargetSize == 5_mm);

    requireUndo(history, part.document);
    // EXACT canonical equality, not "about 10".
    CHECK(definitionOf(part.document, control).mesh.sizing.globalTargetSize == 10_mm);

    requireRedo(history, part.document);
    CHECK(definitionOf(part.document, control).mesh.sizing.globalTargetSize == 5_mm);

    // And clearing it back to the default round-trips too.
    (void)run<SetGlobalMeshSizeCommand>(history, part.document, control,
                                        std::optional<Length>{std::nullopt});
    CHECK_FALSE(definitionOf(part.document, control).mesh.sizing.globalTargetSize.has_value());
    requireUndo(history, part.document);
    CHECK(definitionOf(part.document, control).mesh.sizing.globalTargetSize == 5_mm);
}

TEST_CASE("MeshingCommand_AUnitEquivalentEditChangesNothing", "[meshing][meshcmd][global]") {
    // 10 mm and 0.01 m are THE SAME canonical quantity. A Length is SI
    // internally, so this is not a conversion question -- the two requests are
    // indistinguishable by the time they reach the model, and recording a
    // semantic change for one would be recording an edit that did not happen.
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    const std::string before = fingerprintOf(part.document, control);
    const std::uint64_t revision = part.document.revision();

    SetGlobalMeshSizeCommand* edit = run<SetGlobalMeshSizeCommand>(
        history, part.document, control, std::optional<Length>{Length::fromSi(0.010)});
    CHECK_FALSE(edit->changedAnything());
    CHECK(fingerprintOf(part.document, control) == before);
    // NO REVISION BUMP, and so nothing downstream is invalidated.
    CHECK(part.document.revision() == revision);
}

TEST_CASE("MeshingCommand_ANoOpEditCostsNothingButAHistoryEntry",
          "[meshing][meshcmd][global]") {
    // The brief prefers a no-op to leave no history entry. The framework
    // records every command whose execute() succeeded -- which is the same
    // behaviour P15's material edit has -- so what a no-op avoids here is the
    // part that matters: no mutation, no revision bump, and therefore no mesh
    // invalidation. The history entry is accepted rather than special-cased in
    // one module, and its undo and redo are themselves no-ops.
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    const std::string before = fingerprintOf(part.document, control);
    const std::uint64_t revision = part.document.revision();

    SetGlobalMeshSizeCommand* same = run<SetGlobalMeshSizeCommand>(
        history, part.document, control, std::optional<Length>{10_mm});
    CHECK_FALSE(same->changedAnything());
    CHECK(part.document.revision() == revision);
    CHECK(fingerprintOf(part.document, control) == before);

    requireUndo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == before);
    requireRedo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == before);
}

TEST_CASE("MeshingCommand_AnInvalidSizeFailsBeforeTouchingAnything",
          "[meshing][meshcmd][atomic]") {
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 2_mm);

    const std::string before = fingerprintOf(part.document, control);
    const std::size_t undoDepth = history.undoCount();
    const std::size_t redoDepth = history.redoCount();
    const std::uint64_t revision = part.document.revision();

    const std::array<Length, 4> invalid{Length::fromSi(0.0), Length::fromSi(-1e-3),
                                        Length::fromSi(std::numeric_limits<double>::quiet_NaN()),
                                        Length::fromSi(std::numeric_limits<double>::infinity())};
    for (const Length size : invalid) {
        INFO("size " << size.si());
        const Error error = runExpectingFailure<SetGlobalMeshSizeCommand>(
            history, part.document, control, std::optional<Length>{size});
        CHECK(error.code == ErrorCode::InvalidArgument);
        // EVERY ONE OF THESE must hold after a refusal, and all four are
        // separate ways the atomicity could be broken.
        CHECK(fingerprintOf(part.document, control) == before);
        CHECK(history.undoCount() == undoDepth);
        CHECK(history.redoCount() == redoDepth);
        CHECK(part.document.revision() == revision);
    }

    // An invalid local size, the same way.
    CHECK(runExpectingFailure<EditLocalMeshSizingCommand>(history, part.document, control,
                                                          part.top(), Length::fromSi(-1.0))
              .code == ErrorCode::InvalidArgument);
    CHECK(fingerprintOf(part.document, control) == before);
    CHECK(history.undoCount() == undoDepth);
}

// ---------------------------------------------------------------------------
// Local sizing, keyed by the face it refines
// ---------------------------------------------------------------------------

TEST_CASE("MeshingCommand_LocalSizingAddEditRemoveAreExactAndKeyedByFace",
          "[meshing][meshcmd][local]") {
    // The brief's fixture: L1 on face F at 2 mm, edited to 1 mm, undone, redone.
    // The identity under test is the FACE, which is P16-SIZE-001's contract --
    // it refuses two controls on one face -- so there is no synthetic ID to be
    // minted differently on a redo.
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    const std::string s0 = fingerprintOf(part.document, control);

    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 2_mm);
    const std::string s1 = fingerprintOf(part.document, control);
    const MeshControl* added = meshing::findMeshControl(part.document, control);
    REQUIRE(added->localSizing(part.top()) != nullptr);
    CHECK(added->localSizing(part.top())->targetSize == 2_mm);
    CHECK(added->localSizing(part.top())->face == part.top());

    (void)run<EditLocalMeshSizingCommand>(history, part.document, control, part.top(), 1_mm);
    const std::string s2 = fingerprintOf(part.document, control);
    CHECK(meshing::findMeshControl(part.document, control)->localSizing(part.top())->targetSize ==
          1_mm);

    requireUndo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == s1);
    CHECK(meshing::findMeshControl(part.document, control)->localSizing(part.top())->targetSize ==
          2_mm);

    requireRedo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == s2);

    // Remove, and undo restores the same face reference AND the same size.
    (void)run<RemoveLocalMeshSizingCommand>(history, part.document, control, part.top());
    CHECK(meshing::findMeshControl(part.document, control)->localSizing(part.top()) == nullptr);
    requireUndo(history, part.document);
    const MeshControl* restored = meshing::findMeshControl(part.document, control);
    REQUIRE(restored->localSizing(part.top()) != nullptr);
    CHECK(restored->localSizing(part.top())->face == part.top());
    CHECK(restored->localSizing(part.top())->targetSize == 1_mm);
    CHECK(fingerprintOf(part.document, control) == s2);

    // All the way back.
    requireUndo(history, part.document);  // undo the edit
    requireUndo(history, part.document);  // undo the add
    CHECK(fingerprintOf(part.document, control) == s0);
}

TEST_CASE("MeshingCommand_LocalSizingRefusesWhatTheModelForbids",
          "[meshing][meshcmd][local][validation]") {
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 2_mm);
    const std::string before = fingerprintOf(part.document, control);
    const std::size_t depth = history.undoCount();

    // TWO CONTROLS ON ONE FACE: P16-SIZE-001's rule, refused at the point of
    // the mistake rather than surfacing later from inside a validator.
    const Error duplicate = runExpectingFailure<AddLocalMeshSizingCommand>(
        history, part.document, control, part.top(), 1_mm);
    CHECK(duplicate.code == ErrorCode::AlreadyExists);
    CHECK_THAT(duplicate.message, ContainsSubstring("already exists"));

    // Editing or removing a face that has no control.
    CHECK(runExpectingFailure<EditLocalMeshSizingCommand>(history, part.document, control,
                                                          part.side(0), 1_mm)
              .code == ErrorCode::NotFound);
    CHECK(runExpectingFailure<RemoveLocalMeshSizingCommand>(history, part.document, control,
                                                            part.side(0))
              .code == ErrorCode::NotFound);

    CHECK(fingerprintOf(part.document, control) == before);
    CHECK(history.undoCount() == depth);
}

TEST_CASE("MeshingCommand_AGeometryReferenceSurvivesUndoAndRedoUnchanged",
          "[meshing][meshcmd][local][reference]") {
    // The command stores the FaceName -- the intent -- and never what it
    // currently resolves to. So undo and redo move the same reference about,
    // and nothing in the history depends on the mesh that existed at the time.
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    const FaceName target = part.side(2);

    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, target, 1.5_mm);
    const LocalMeshSizing* stored =
        meshing::findMeshControl(part.document, control)->localSizing(target);
    REQUIRE(stored != nullptr);
    CHECK(stored->face == target);

    requireUndo(history, part.document);
    requireRedo(history, part.document);
    const LocalMeshSizing* again =
        meshing::findMeshControl(part.document, control)->localSizing(target);
    REQUIRE(again != nullptr);
    // The SAME reference, field for field, not an equivalent one.
    CHECK(again->face == target);
    CHECK(again->face.feature == target.feature);
    CHECK(again->face.face.role == target.face.role);
    CHECK(again->face.face.entity == target.face.entity);
    CHECK(again->targetSize == 1.5_mm);
}

// ---------------------------------------------------------------------------
// Boundary sets
// ---------------------------------------------------------------------------

TEST_CASE("MeshingCommand_BoundarySetAddEditRemoveKeepItsIdentity",
          "[meshing][meshcmd][boundary]") {
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    const BoundarySetId setId = BoundarySetId::fromValue(4U);
    const NamedBoundarySet fixed{.id = setId, .name = "fixed_end", .faces = {part.side(0)}};

    (void)run<AddBoundarySetCommand>(history, part.document, control, fixed);
    const std::string s1 = fingerprintOf(part.document, control);
    REQUIRE(meshing::findMeshControl(part.document, control)->boundarySet(setId) != nullptr);
    CHECK(meshing::findMeshControl(part.document, control)->boundarySet(setId)->name ==
          "fixed_end");

    // A rename and a selection change, keeping the identity.
    const NamedBoundarySet renamed{
        .id = setId, .name = "clamped", .faces = {part.side(0), part.side(2)}};
    (void)run<EditBoundarySetCommand>(history, part.document, control, renamed);
    const NamedBoundarySet* edited =
        meshing::findMeshControl(part.document, control)->boundarySet(setId);
    REQUIRE(edited != nullptr);
    CHECK(edited->id == setId);
    CHECK(edited->name == "clamped");
    CHECK(edited->faces.size() == 2U);

    requireUndo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == s1);

    // Remove, and undo restores the SAME identity rather than minting one.
    requireRedo(history, part.document);
    (void)run<RemoveBoundarySetCommand>(history, part.document, control, setId);
    CHECK(meshing::findMeshControl(part.document, control)->boundarySet(setId) == nullptr);
    requireUndo(history, part.document);
    const NamedBoundarySet* back =
        meshing::findMeshControl(part.document, control)->boundarySet(setId);
    REQUIRE(back != nullptr);
    CHECK(back->id == setId);
    CHECK(back->name == "clamped");

    // And the refusals.
    const std::size_t depth = history.undoCount();
    CHECK(runExpectingFailure<AddBoundarySetCommand>(history, part.document, control, renamed)
              .code == ErrorCode::AlreadyExists);
    CHECK(runExpectingFailure<RemoveBoundarySetCommand>(history, part.document, control,
                                                        BoundarySetId::fromValue(99U))
              .code == ErrorCode::NotFound);
    CHECK(history.undoCount() == depth);
}

// ---------------------------------------------------------------------------
// The stacks
// ---------------------------------------------------------------------------

TEST_CASE("MeshingCommand_ANewCommandDiscardsTheRedoBranch", "[meshing][meshcmd][stack]") {
    // S0 -A-> S1 -B-> S2, undo to S1, then C. Redo of B must be gone.
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);
    const std::string s0 = fingerprintOf(part.document, control);

    (void)run<SetGlobalMeshSizeCommand>(history, part.document, control,
                                        std::optional<Length>{8_mm});
    const std::string s1 = fingerprintOf(part.document, control);
    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 2_mm);
    const std::string s2 = fingerprintOf(part.document, control);

    requireUndo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == s1);
    CHECK(history.canRedo());

    (void)run<SetGlobalMeshSizeCommand>(history, part.document, control,
                                        std::optional<Length>{6_mm});
    const std::string s3 = fingerprintOf(part.document, control);

    // B IS UNREACHABLE. The branch it belonged to was discarded.
    CHECK_FALSE(history.canRedo());
    CHECK(history.redoCount() == 0U);
    CHECK(fingerprintOf(part.document, control) == s3);
    CHECK_FALSE(s3 == s2);

    // And the surviving history still walks back to the beginning.
    requireUndo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == s1);
    requireUndo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == s0);
}

TEST_CASE("MeshingCommand_AMultiStepSequenceUndoesAndRedoesExactly",
          "[meshing][meshcmd][stack]") {
    // The brief's mandatory sequence: set global, add A, add B, edit A,
    // remove B. Undo all the way to the start, then redo all the way forward,
    // comparing the canonical intent at every step.
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);

    std::vector<std::string> states{fingerprintOf(part.document, control)};
    (void)run<SetGlobalMeshSizeCommand>(history, part.document, control,
                                        std::optional<Length>{7_mm});
    states.push_back(fingerprintOf(part.document, control));
    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 3_mm);
    states.push_back(fingerprintOf(part.document, control));
    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.side(1), 2_mm);
    states.push_back(fingerprintOf(part.document, control));
    (void)run<EditLocalMeshSizingCommand>(history, part.document, control, part.top(), 1_mm);
    states.push_back(fingerprintOf(part.document, control));
    (void)run<RemoveLocalMeshSizingCommand>(history, part.document, control, part.side(1));
    states.push_back(fingerprintOf(part.document, control));

    // Every state must differ from the last, or the sequence is not testing
    // five distinct edits.
    for (std::size_t step = 1U; step < states.size(); ++step) {
        INFO("step " << step);
        CHECK_FALSE(states[step] == states[step - 1U]);
    }

    for (std::size_t step = states.size() - 1U; step > 0U; --step) {
        requireUndo(history, part.document);
        INFO("after undoing to step " << (step - 1U));
        CHECK(fingerprintOf(part.document, control) == states[step - 1U]);
    }
    // ONE ENTRY LEFT, and exactly one: the create that made the control. The
    // five edits consumed five entries and no more, which is the part worth
    // asserting -- an edit that recorded two steps, or none, would show here.
    CHECK(history.undoCount() == 1U);

    for (std::size_t step = 1U; step < states.size(); ++step) {
        requireRedo(history, part.document);
        INFO("after redoing to step " << step);
        CHECK(fingerprintOf(part.document, control) == states[step]);
    }
    CHECK_FALSE(history.canRedo());
}

TEST_CASE("MeshingCommand_DescriptionsNameTheIntentAndNotAnyMesh",
          "[meshing][meshcmd][stack]") {
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);

    std::vector<std::string> descriptions{history.undoDescription().value()};
    CHECK_THAT(descriptions.back(), ContainsSubstring("Create meshing control"));

    (void)run<SetGlobalMeshSizeCommand>(history, part.document, control,
                                        std::optional<Length>{5_mm});
    descriptions.push_back(history.undoDescription().value());
    CHECK_THAT(descriptions.back(), ContainsSubstring("global mesh size"));
    // THE VALUE, so the description describes this edit and not merely its
    // kind -- a history of five "Set global mesh size" entries is not a
    // history a user can read.
    CHECK_THAT(descriptions.back(), ContainsSubstring("5 mm"));

    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 2_mm);
    descriptions.push_back(history.undoDescription().value());
    CHECK_THAT(descriptions.back(), ContainsSubstring("local mesh sizing"));
    CHECK_THAT(descriptions.back(), ContainsSubstring("2 mm"));

    (void)run<AddBoundarySetCommand>(
        history, part.document, control,
        NamedBoundarySet{
            .id = BoundarySetId::fromValue(1U), .name = "loaded", .faces = {part.top()}});
    descriptions.push_back(history.undoDescription().value());
    CHECK_THAT(descriptions.back(), ContainsSubstring("loaded"));

    // AND NOT ONE OF THEM MENTIONS A MESH. A description names the intent; how
    // many tetrahedra it happens to produce is derived, is not yet known when
    // the description is written, and would change the text of a history entry
    // after the fact.
    for (const std::string& text : descriptions) {
        INFO(text);
        CHECK_THAT(text, !ContainsSubstring("tetrahedr"));
        CHECK_THAT(text, !ContainsSubstring("element"));
        CHECK_THAT(text, !ContainsSubstring("node"));
        CHECK_THAT(text, !ContainsSubstring("triangle"));
    }
}

// ---------------------------------------------------------------------------
// Determinism
// ---------------------------------------------------------------------------

TEST_CASE("MeshingCommand_TheSameSequenceGivesTheSameCanonicalState",
          "[meshing][meshcmd][determinism]") {
    const auto play = []() {
        Part part;
        CommandHistory history;
        const MeshControlId control = makeControl(part, history);
        (void)run<SetGlobalMeshSizeCommand>(history, part.document, control,
                                            std::optional<Length>{6_mm});
        (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.side(2), 2_mm);
        (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 1_mm);
        (void)run<AddBoundarySetCommand>(
            history, part.document, control,
            NamedBoundarySet{
                .id = BoundarySetId::fromValue(3U), .name = "fixed", .faces = {part.bottom()}});
        std::vector<std::string> trace{fingerprintOf(part.document, control)};
        requireUndo(history, part.document);
        trace.push_back(fingerprintOf(part.document, control));
        requireRedo(history, part.document);
        trace.push_back(fingerprintOf(part.document, control));
        return trace;
    };

    const std::vector<std::string> first = play();
    const std::vector<std::string> second = play();
    REQUIRE(first.size() == second.size());
    // The control IDs come out the same because allocation is deterministic
    // for the same document construction, and the enumeration is ordered
    // rather than hashed -- so the whole trace is comparable.
    CHECK(first == second);
}

// ---------------------------------------------------------------------------
// Invalidation, and what an undo actually restores
// ---------------------------------------------------------------------------
//
// These are the tests that distinguish this milestone from a plain undo stack.
// A command never meshes, so what an undo restores is INTENT; the mesh that
// intent describes is recomputed on the next explicit request. The matrix below
// is the brief's invalidation table, made executable.

TEST_CASE("MeshingCommand_ASizeEditMakesTheHeldMeshStaleAndNothingElse",
          "[meshing][meshcmd][invalidate]") {
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);

    CHECK(mesher.currency(part.document, control) == MeshCurrency::NoMesh);
    const Result<const VolumeMesh*> first =
        mesher.generate(part.document, part.regenerator, control);
    INFO((first ? std::string{} : first.error().message));
    REQUIRE(first.has_value());
    const std::size_t elementsAt10mm = (*first)->mesh().elementCount();
    CHECK(elementsAt10mm > 0U);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);

    // A GLOBAL SIZE EDIT. This is the case that was broken before the Mesher
    // existed: the geometry has not moved, so a geometry-revision comparison
    // sees nothing, and the mesh went on looking current while describing a
    // discretisation nobody asked for any more.
    (void)run<SetGlobalMeshSizeCommand>(history, part.document, control,
                                        std::optional<Length>{4_mm});
    CHECK(mesher.currency(part.document, control) == MeshCurrency::StaleIntent);
    // STILL INSPECTABLE. Stale is old, not wrong, and P16-VIZ-001's stale view
    // needs the elements to still be there.
    REQUIRE(mesher.mesh(control) != nullptr);
    CHECK(mesher.mesh(control)->mesh().elementCount() == elementsAt10mm);

    // An undo returns the intent the mesh was built from, so it is current
    // again -- WITHOUT having remeshed, and without the history ever holding
    // an element.
    requireUndo(history, part.document);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);
    CHECK(mesher.mesh(control)->mesh().elementCount() == elementsAt10mm);

    requireRedo(history, part.document);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::StaleIntent);

    // And generating now produces a mesh of the SMALLER size: finer, so more
    // elements. This is the proof that the intent reached the mesher rather
    // than a cached argument.
    const Result<const VolumeMesh*> finer =
        mesher.generate(part.document, part.regenerator, control);
    REQUIRE(finer.has_value());
    CHECK((*finer)->mesh().elementCount() > elementsAt10mm);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);
}

TEST_CASE("MeshingCommand_ALocalSizeEditInvalidatesAndARenameDoesNot",
          "[meshing][meshcmd][invalidate]") {
    // THE PRECISION REQUIREMENT. "Invalidate on any edit" would be easy and
    // would remesh a hundred thousand elements because somebody corrected a
    // spelling. These two edits bump the SAME object revision; only one of
    // them can change a tetrahedron.
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    const BoundarySetId setId = BoundarySetId::fromValue(2U);
    (void)run<AddBoundarySetCommand>(
        history, part.document, control,
        NamedBoundarySet{.id = setId, .name = "fixed", .faces = {part.bottom()}});
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    REQUIRE(mesher.currency(part.document, control) == MeshCurrency::Current);
    const std::uint64_t afterMeshing = part.document.revision();

    // A RENAME. The document revision moves, and the mesh does not become
    // stale, because no sizing changed.
    (void)run<EditBoundarySetCommand>(
        history, part.document, control,
        NamedBoundarySet{.id = setId, .name = "clamped", .faces = {part.bottom()}});
    CHECK(part.document.revision() > afterMeshing);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);

    // A LOCAL SIZE. Same kind of edit to the same object; this one does.
    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 3_mm);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::StaleIntent);

    requireUndo(history, part.document);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);
}

TEST_CASE("MeshingCommand_AThresholdEditDatesTheReportAndNotTheMesh",
          "[meshing][meshcmd][invalidate]") {
    // A threshold decides how a number is CLASSIFIED and can never change the
    // number (P16-QUALITY-001). So the mesh stays current and only the report
    // goes out of date -- two separate questions, and collapsing them into one
    // would remesh for a policy change.
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    REQUIRE(mesher.quality(control) != nullptr);
    CHECK(mesher.qualityDescribesCurrentPolicy(part.document, control));

    MeshControlDefinition stricter = definitionOf(part.document, control);
    stricter.quality.limits[QualityMetric::TetMinDihedralAngle] =
        QualityThreshold{.warning = 0.3, .failure = 0.1};
    (void)run<SetMeshControlDefinitionCommand>(history, part.document, control, stricter);

    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);
    CHECK_FALSE(mesher.qualityDescribesCurrentPolicy(part.document, control));

    requireUndo(history, part.document);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);
    CHECK(mesher.qualityDescribesCurrentPolicy(part.document, control));
}

TEST_CASE("MeshingCommand_AGeometryChangeIsStaleForADifferentReason",
          "[meshing][meshcmd][invalidate]") {
    // The two kinds of staleness are reported separately because they mean
    // different things to a user: one says the ELEMENTS are wrong, the other
    // says the SHAPE is. Reducing both to "stale" would make the mesh view
    // unable to say which.
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    REQUIRE(mesher.currency(part.document, control) == MeshCurrency::Current);

    part.setDepth(25_mm);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::StaleGeometry);
    CHECK_FALSE(describesTheModel(mesher.currency(part.document, control)));

    // AND IT STAYS STALE WHEN THE SHAPE COMES BACK, which is worth asserting
    // because the opposite is the intuitive guess and it is wrong.
    // `geometryRevision` mixes the REVISION COUNTERS of a feature's dependency
    // sources (P16-GEOM-001), and a counter only moves forward -- so restoring
    // 10 mm produces the original solid under a new stamp.
    //
    // CONSERVATIVE, AND DELIBERATELY SO. The cost of being wrong this way is
    // one remesh that was not strictly needed; the cost of the other way is a
    // mesh presented as describing a model it does not. The milestone's
    // invalidation precision is about not remeshing for edits that CANNOT
    // change an element -- a boundary rename, a threshold change -- and this
    // edit genuinely did change the geometry twice.
    part.setDepth(10_mm);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::StaleGeometry);

    // Regenerating is what makes it current, and the mesh it produces is the
    // original one: same shape, same sizing, same element count.
    const std::size_t original = mesher.mesh(control)->mesh().elementCount();
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);
    CHECK(mesher.mesh(control)->mesh().elementCount() == original);
}

TEST_CASE("MeshingCommand_DeletingAControlLeavesNoMeshBehindIt",
          "[meshing][meshcmd][invalidate]") {
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());

    (void)run<DeleteMeshControlCommand>(history, part.document, control);
    // A mesh of a control that no longer exists is not stale, it is
    // meaningless -- but the mesher is derived state and not notified by the
    // document, so until the owner forgets it the currency must say the intent
    // is gone rather than claim the mesh is current.
    CHECK(mesher.currency(part.document, control) == MeshCurrency::StaleIntent);
    mesher.forget(control);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::NoMesh);
    CHECK(mesher.mesh(control) == nullptr);
    CHECK(mesher.heldMeshCount() == 0U);

    // An undo restores the intent, and the mesh does NOT come back: it was
    // never in the history.
    requireUndo(history, part.document);
    REQUIRE(meshing::findMeshControl(part.document, control) != nullptr);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::NoMesh);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);
}

TEST_CASE("MeshingCommand_AFailedGenerationLeavesTheIntentAndTheHistoryIntact",
          "[meshing][meshcmd][atomic]") {
    // Meshing is not a command, so its failure cannot touch the history -- and
    // this test is what makes that a verified property rather than an
    // assertion about the call graph.
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    const std::size_t elements = mesher.mesh(control)->mesh().elementCount();

    const std::string before = fingerprintOf(part.document, control);
    const std::size_t undoDepth = history.undoCount();

    // A control that names a body with no geometry. The document stays valid;
    // the mesher simply cannot build this one.
    MeshControlDefinition orphaned = part.definition();
    orphaned.body = ObjectId::fromValue(987654U);
    CreateMeshControlCommand* create =
        run<CreateMeshControlCommand>(history, part.document, "Orphan", orphaned);
    const MeshControlId bad = create->meshControlId();

    const Result<const VolumeMesh*> failed =
        mesher.generate(part.document, part.regenerator, bad);
    REQUIRE_FALSE(failed.has_value());
    CHECK(mesher.currency(part.document, bad) == MeshCurrency::GenerationFailed);
    CHECK(mesher.lastFailure(bad) != nullptr);
    CHECK(mesher.mesh(bad) == nullptr);

    // THE OTHER CONTROL IS UNTOUCHED, in its intent and in its mesh.
    CHECK(fingerprintOf(part.document, control) == before);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);
    CHECK(mesher.mesh(control)->mesh().elementCount() == elements);
    CHECK(history.undoCount() == undoDepth + 1U);
}

TEST_CASE("MeshingCommand_AFailedRegenerationKeepsTheMeshItCouldNotReplace",
          "[meshing][meshcmd][atomic]") {
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    const std::size_t elements = mesher.mesh(control)->mesh().elementCount();

    // Point the control at nothing, then ask again. The attempt fails.
    MeshControlDefinition broken = definitionOf(part.document, control);
    broken.body = ObjectId::fromValue(424242U);
    (void)run<SetMeshControlDefinitionCommand>(history, part.document, control, broken);
    REQUIRE_FALSE(mesher.generate(part.document, part.regenerator, control).has_value());

    // THE OLD MESH SURVIVED. A failed remesh must not destroy what the user
    // could still inspect, and the failure is reported rather than hidden
    // behind a mesh that no longer matches anything.
    REQUIRE(mesher.mesh(control) != nullptr);
    CHECK(mesher.mesh(control)->mesh().elementCount() == elements);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::GenerationFailed);

    // And undoing the edit clears the failure on the next attempt.
    requireUndo(history, part.document);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::GenerationFailed);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);
    CHECK(mesher.lastFailure(control) == nullptr);
}

TEST_CASE("MeshingCommand_RemeshingAfterAnUndoRedoChainFollowsTheRestoredIntent",
          "[meshing][meshcmd][invalidate]") {
    // THE WHOLE POINT OF THE MILESTONE, in one test. Mesh, edit, mesh, undo,
    // mesh: the third mesh must match the FIRST, because the intent does --
    // and it must match by element count, which is derived from the sizing and
    // could not match by accident if the undo had restored the wrong settings.
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);

    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    const std::size_t coarse = mesher.mesh(control)->mesh().elementCount();

    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 2_mm);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    const std::size_t refined = mesher.mesh(control)->mesh().elementCount();
    // The refinement must actually have done something, or the rest of this
    // test compares two identical numbers and proves nothing.
    REQUIRE(refined > coarse);

    requireUndo(history, part.document);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    CHECK(mesher.mesh(control)->mesh().elementCount() == coarse);

    requireRedo(history, part.document);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    CHECK(mesher.mesh(control)->mesh().elementCount() == refined);
}

// ---------------------------------------------------------------------------
// What a history step actually costs
// ---------------------------------------------------------------------------
//
// The milestone's rule is a claim about SIZE, so it is measured rather than
// asserted. The numbers below are reported through WARN so the evidence
// directory can cite them instead of quoting an estimate.

namespace {

/// The bytes a definition's own members and their vector storage occupy.
///
/// Per-node allocator overhead for the threshold map is deliberately NOT
/// counted: it is an implementation detail of `std::map` and would make the
/// figure a measurement of libstdc++ rather than of the intent. Everything
/// that scales with what the user created is counted.
[[nodiscard]] std::size_t intentFootprint(const MeshControlDefinition& definition) {
    std::size_t bytes = sizeof(MeshControlDefinition);
    bytes += definition.mesh.sizing.local.capacity() * sizeof(LocalMeshSizing);
    for (const NamedBoundarySet& set : definition.boundarySets) {
        bytes += sizeof(NamedBoundarySet) + set.name.capacity();
        bytes += set.faces.capacity() * sizeof(FaceName);
    }
    bytes += definition.quality.limits.size() *
             sizeof(std::pair<const QualityMetric, QualityThreshold>);
    return bytes;
}

/// The bytes the mesh's own arrays occupy.
[[nodiscard]] std::size_t meshFootprint(const meshing::Mesh& mesh) {
    return mesh.nodeCount() * sizeof(meshing::Node) +
           mesh.tetrahedra().size() * sizeof(meshing::Tetrahedron) +
           mesh.triangles().size() * sizeof(meshing::Triangle);
}

} // namespace

TEST_CASE("MeshingCommand_AHistoryStepCostsTheIntentAndNotTheMesh",
          "[meshing][meshcmd][payload]") {
    Tube part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 3_mm);
    (void)run<AddBoundarySetCommand>(
        history, part.document, control,
        NamedBoundarySet{
            .id = BoundarySetId::fromValue(1U), .name = "fixed_end", .faces = {part.bottom()}});

    // A command's own object, and the before/after pair that makes its undo
    // exact. This is the whole of what a history entry holds.
    const std::size_t intent = intentFootprint(definitionOf(part.document, control));
    const std::size_t step = sizeof(SetGlobalMeshSizeCommand) + 2U * intent;

    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    const std::size_t coarseMesh = meshFootprint(mesher.mesh(control)->mesh());
    const std::size_t coarseElements = mesher.mesh(control)->mesh().elementCount();

    // NOW REFINE, which grows the mesh and must not move the step.
    (void)run<SetGlobalMeshSizeCommand>(history, part.document, control,
                                        std::optional<Length>{1.5_mm});
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    const std::size_t fineMesh = meshFootprint(mesher.mesh(control)->mesh());
    const std::size_t fineElements = mesher.mesh(control)->mesh().elementCount();
    // STRICT GROWTH, and no particular multiple.
    //
    // How much a volume target can grow a mesh is set by the BOUNDARY it has
    // to conform to, which is `SurfaceMeshControls`' business and not this
    // test's: measured here, 10 mm to 1.5 mm takes 504 elements to 932, while
    // the same step on a block moves nothing at all because a planar face is
    // exactly twelve triangles whatever the deflection. Asserting a ratio
    // would be asserting a property of OCCT's triangulator. The claim being
    // measured is that the step did not move while the mesh did, and the
    // figures are reported so the size claim is read off a measurement.
    REQUIRE(fineElements > coarseElements);
    REQUIRE(fineMesh > coarseMesh);

    const std::size_t stepAfter =
        sizeof(SetGlobalMeshSizeCommand) + 2U * intentFootprint(definitionOf(part.document, control));

    // THE MEASUREMENT. A history step for the same control is the same size
    // whether the mesh it describes has hundreds of elements or thousands,
    // because its size is a function of the CONTROLS and nothing else.
    CHECK(stepAfter == step);
    CHECK(step < fineMesh);

    WARN(std::format(
        "history step {} B (command {} B + 2 x intent {} B) | mesh {} B at {} elements, "
        "{} B at {} elements | step is {:.4g}% of the coarse mesh and {:.4g}% of the fine one",
        step, sizeof(SetGlobalMeshSizeCommand), intent, coarseMesh, coarseElements, fineMesh,
        fineElements, 100.0 * static_cast<double>(step) / static_cast<double>(coarseMesh),
        100.0 * static_cast<double>(step) / static_cast<double>(fineMesh)));
}

TEST_CASE("MeshingCommand_NoCommandIsLargeEnoughToHoldAMesh", "[meshing][meshcmd][payload]") {
    // A BOUND, NOT A GUESS. Each command's own object is a control ID, its own
    // argument and two optional definitions; none of them can be holding mesh
    // arrays by value, and the figures are reported so a future change that
    // made one of them grow would be visible rather than silent.
    //
    // This cannot catch a POINTER to a mesh, which is why it is not the only
    // evidence: MeshingCommand_DeletingAControlLeavesNoMeshBehindIt asserts
    // that an undo restores no mesh at all.
    const std::size_t definition = sizeof(MeshControlDefinition);
    CHECK(sizeof(SetGlobalMeshSizeCommand) < 4U * definition);
    CHECK(sizeof(AddLocalMeshSizingCommand) < 4U * definition);
    CHECK(sizeof(EditLocalMeshSizingCommand) < 4U * definition);
    CHECK(sizeof(RemoveLocalMeshSizingCommand) < 4U * definition);
    CHECK(sizeof(AddBoundarySetCommand) < 4U * definition);
    CHECK(sizeof(EditBoundarySetCommand) < 4U * definition);
    CHECK(sizeof(RemoveBoundarySetCommand) < 4U * definition);
    CHECK(sizeof(SetMeshControlDefinitionCommand) < 4U * definition);
    CHECK(sizeof(CreateMeshControlCommand) < 4U * definition);
    CHECK(sizeof(DeleteMeshControlCommand) < 4U * definition);

    WARN(std::format("MeshControlDefinition {} B | SetGlobalMeshSize {} B | AddLocalMeshSizing "
                     "{} B | AddBoundarySet {} B | SetMeshControlDefinition {} B | "
                     "CreateMeshControl {} B | DeleteMeshControl {} B",
                     definition, sizeof(SetGlobalMeshSizeCommand),
                     sizeof(AddLocalMeshSizingCommand), sizeof(AddBoundarySetCommand),
                     sizeof(SetMeshControlDefinitionCommand), sizeof(CreateMeshControlCommand),
                     sizeof(DeleteMeshControlCommand)));
}

TEST_CASE("MeshingCommand_ALongHistoryStaysProportionalToTheEdits",
          "[meshing][meshcmd][payload]") {
    // Fifty edits with a mesh held throughout. The history grows by fifty
    // steps and the mesh is generated once, so nothing here should touch it --
    // and the fiftieth undo must still be exact, which is the part a cheap
    // implementation would get wrong by sharing state between steps.
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    const std::size_t elements = mesher.mesh(control)->mesh().elementCount();

    std::vector<std::string> states{fingerprintOf(part.document, control)};
    for (std::size_t step = 0U; step < 50U; ++step) {
        // Sizes that are all distinct and all valid, so every edit is a real
        // change and the fingerprints form a strictly growing trail.
        const Length size = Length::fromSi(0.004 + 0.0001 * static_cast<double>(step));
        (void)run<SetGlobalMeshSizeCommand>(history, part.document, control,
                                            std::optional<Length>{size});
        states.push_back(fingerprintOf(part.document, control));
    }
    REQUIRE(history.undoCount() == 51U);
    // THE MESH WAS NEVER TOUCHED by fifty intent edits.
    CHECK(mesher.mesh(control)->mesh().elementCount() == elements);
    CHECK(mesher.currency(part.document, control) == MeshCurrency::StaleIntent);

    for (std::size_t step = states.size() - 1U; step > 0U; --step) {
        requireUndo(history, part.document);
        INFO("after undoing to step " << (step - 1U));
        CHECK(fingerprintOf(part.document, control) == states[step - 1U]);
    }
    // Back to the intent the mesh was built from, so it is current again --
    // after fifty undos, and still without a remesh.
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);
    CHECK(mesher.mesh(control)->mesh().elementCount() == elements);
}

// ---------------------------------------------------------------------------
// Geometry references across a topology change
// ---------------------------------------------------------------------------
//
// THE P21 BOUNDARY, and the milestone's most consequential test. A command
// stores the FaceName the user chose. When a model edit makes that face stop
// existing, the right behaviour is for the reference to stay what it was and
// be reported as unresolved -- NOT to quietly rebind to whichever face is
// nearest now, which would silently change what the user asked for and would
// be undetectable afterwards.

namespace {

/// The one local control's resolution, read from the generated mesh.
///
/// Through the production API: `VolumeMesh::sizing()` keeps the derived
/// `ResolvedSizing` that the sizing layer produced, so the state is the one
/// the mesher actually acted on and not a second opinion computed by the test.
[[nodiscard]] const meshing::LocalSizingResolution& onlyResolution(const VolumeMesh& mesh) {
    REQUIRE(mesh.sizing().local.size() == 1U);
    return mesh.sizing().local.front();
}

} // namespace

TEST_CASE("MeshingCommand_AnUnresolvedFaceReferenceSurvivesUndoAndRedoUnrebound",
          "[meshing][meshcmd][reference]") {
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    const FaceName target = part.side(2);

    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, target, 2_mm);
    const Result<const VolumeMesh*> before =
        mesher.generate(part.document, part.regenerator, control);
    INFO((before ? std::string{} : before.error().message));
    REQUIRE(before.has_value());
    REQUIRE(onlyResolution(**before).state == meshing::SizingSelectionState::Resolved);
    CHECK(onlyResolution(**before).face == target);

    // THE TOPOLOGY CHANGE. The extrude is re-profiled onto a circle, so the
    // body is a cylinder with ONE side face and the line that generated the
    // control's face does not exist in the profile any more. The feature's own
    // ObjectId does not move and the `Side` role still means something --
    // which is exactly the case a nearest-face rebind would get wrong without
    // looking wrong.
    const EntityId replacement = part.setProfileToCircle();
    REQUIRE_FALSE(replacement == *target.face.entity);

    // MESHING NOW REFUSES, and refusing is right. `resolveSizing` reports an
    // unresolved control rather than failing, and leaves the decision to its
    // caller; `volumeMeshFor` decides not to proceed. Quietly meshing while
    // ignoring a refinement the user asked for would hand back a mesh that
    // looks like the requested one and is not.
    const Result<const VolumeMesh*> after =
        mesher.generate(part.document, part.regenerator, control);
    REQUIRE_FALSE(after.has_value());
    CHECK_THAT(after.error().message, ContainsSubstring("does not resolve"));
    CHECK(mesher.currency(part.document, control) == MeshCurrency::GenerationFailed);

    // THE REFERENCE DID NOT MOVE. Not to the circle, not to anything: the
    // canonical intent is exactly what the user chose, and the failure is
    // reported instead of repaired.
    const LocalMeshSizing* kept =
        meshing::findMeshControl(part.document, control)->localSizing(target);
    REQUIRE(kept != nullptr);
    CHECK(kept->face == target);
    CHECK_FALSE(kept->face.face.entity == replacement);
    // And the mesh from before the edit is still there to look at.
    REQUIRE(mesher.mesh(control) != nullptr);

    // UNDO. The control goes away, so the cylinder meshes cleanly -- which
    // proves the refusal above was caused by that control and not by the
    // re-profiling.
    requireUndo(history, part.document);
    CHECK(meshing::findMeshControl(part.document, control)->localSizing(target) == nullptr);
    const Result<const VolumeMesh*> withoutControl =
        mesher.generate(part.document, part.regenerator, control);
    INFO((withoutControl ? std::string{} : withoutControl.error().message));
    REQUIRE(withoutControl.has_value());
    CHECK((*withoutControl)->sizing().local.empty());
    CHECK(mesher.currency(part.document, control) == MeshCurrency::Current);

    // REDO. The canonical reference must come back identical -- the same
    // feature, the same role, the same dead entity -- and must fail the same
    // way, deterministically.
    requireRedo(history, part.document);
    const LocalMeshSizing* restored =
        meshing::findMeshControl(part.document, control)->localSizing(target);
    REQUIRE(restored != nullptr);
    CHECK(restored->face == target);
    CHECK(restored->face.feature == target.feature);
    CHECK(restored->face.face.role == target.face.role);
    CHECK(restored->face.face.entity == target.face.entity);
    CHECK(restored->targetSize == 2_mm);
    CHECK_FALSE(restored->face.face.entity == replacement);

    const Result<const VolumeMesh*> redone =
        mesher.generate(part.document, part.regenerator, control);
    REQUIRE_FALSE(redone.has_value());
    CHECK_THAT(redone.error().message, ContainsSubstring("does not resolve"));
    CHECK(redone.error().message == after.error().message);
}

TEST_CASE("MeshingCommand_AHistoryOutlivesTheMeshesGeneratedUnderIt",
          "[meshing][meshcmd][reference]") {
    // Three generations, then an undo of the FIRST sizing command. The history
    // refers to canonical intent, so no mesh it was recorded beside matters --
    // and a command that had kept a pointer into M1 would be undoing against
    // freed memory by now.
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    const std::string s0 = fingerprintOf(part.document, control);

    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, part.top(), 4_mm);
    const std::string s1 = fingerprintOf(part.document, control);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());

    (void)run<EditLocalMeshSizingCommand>(history, part.document, control, part.top(), 3_mm);
    const std::string s2 = fingerprintOf(part.document, control);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());

    (void)run<SetGlobalMeshSizeCommand>(history, part.document, control,
                                        std::optional<Length>{6_mm});
    const std::string s3 = fingerprintOf(part.document, control);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());

    // All the way back, past three meshes.
    requireUndo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == s2);
    requireUndo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == s1);
    requireUndo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == s0);

    // And forward again.
    requireRedo(history, part.document);
    requireRedo(history, part.document);
    requireRedo(history, part.document);
    CHECK(fingerprintOf(part.document, control) == s3);
}

TEST_CASE("MeshingCommand_AnUndoneCreateDoesNotFreeItsIdForReuse",
          "[meshing][meshcmd][identity]") {
    // An `Id` means stable, persisted, never-reused identity. So the ID of an
    // undone create must not be handed to the next object: if it were, a redo
    // of the create -- which re-inserts under the SAME ID -- would collide
    // with a live object.
    //
    // The history makes that collision unreachable on its own, because the new
    // create clears the redo branch. This asserts the allocator's half of the
    // invariant rather than relying on that.
    Part part;
    CommandHistory history;

    CreateMeshControlCommand* first =
        run<CreateMeshControlCommand>(history, part.document, "First", part.definition());
    const MeshControlId one = first->meshControlId();
    requireUndo(history, part.document);
    CHECK(meshing::findMeshControl(part.document, one) == nullptr);

    CreateMeshControlCommand* second =
        run<CreateMeshControlCommand>(history, part.document, "Second", part.definition());
    const MeshControlId two = second->meshControlId();
    CHECK_FALSE(two == one);
    CHECK(meshing::meshControls(part.document).size() == 1U);

    // The redo branch went with the new command, so the undone create is gone
    // for good rather than waiting to collide.
    CHECK_FALSE(history.canRedo());
}

TEST_CASE("MeshingCommand_TwoControlsOnOneBodyAreIndependent", "[meshing][meshcmd][identity]") {
    // Editing one control must not reach the other, and the mesher keys its
    // held meshes by control -- so two controls on the same body are two
    // meshes with two currencies.
    Part part;
    CommandHistory history;
    Mesher mesher;

    MeshControlDefinition coarse = part.definition();
    coarse.mesh.sizing.globalTargetSize = 10_mm;
    MeshControlDefinition fine = part.definition();
    fine.mesh.sizing.globalTargetSize = 4_mm;
    const MeshControlId a =
        run<CreateMeshControlCommand>(history, part.document, "Coarse", coarse)->meshControlId();
    const MeshControlId b =
        run<CreateMeshControlCommand>(history, part.document, "Fine", fine)->meshControlId();
    REQUIRE_FALSE(a == b);

    REQUIRE(mesher.generate(part.document, part.regenerator, a).has_value());
    REQUIRE(mesher.generate(part.document, part.regenerator, b).has_value());
    CHECK(mesher.heldMeshCount() == 2U);
    const std::string fingerprintA = fingerprintOf(part.document, a);

    // Edit B only.
    (void)run<SetGlobalMeshSizeCommand>(history, part.document, b, std::optional<Length>{2_mm});
    CHECK(mesher.currency(part.document, a) == MeshCurrency::Current);
    CHECK(mesher.currency(part.document, b) == MeshCurrency::StaleIntent);
    CHECK(fingerprintOf(part.document, a) == fingerprintA);

    // Delete B. A's mesh is untouched.
    (void)run<DeleteMeshControlCommand>(history, part.document, b);
    mesher.forget(b);
    CHECK(mesher.heldMeshCount() == 1U);
    CHECK(mesher.currency(part.document, a) == MeshCurrency::Current);
    CHECK(meshing::meshControls(part.document).size() == 1U);

    requireUndo(history, part.document);
    CHECK(meshing::meshControls(part.document).size() == 2U);
    CHECK(mesher.currency(part.document, a) == MeshCurrency::Current);
    // B's intent is back and B has no mesh: the undo restored intent, not a
    // mesh.
    CHECK(mesher.currency(part.document, b) == MeshCurrency::NoMesh);
}

TEST_CASE("MeshingCommand_UndoRestoresTheStoredOrderAndNotOnlyTheSet",
          "[meshing][meshcmd][local]") {
    // WORTH ASSERTING SEPARATELY, because the canonical fingerprint cannot see
    // it. P16-SIZE-001 declares the stored order of local controls
    // meaningless, so `orderedLocalSizing()` sorts and the fingerprint is
    // built from the sorted view -- which means a restore that returned the
    // right SET in the wrong SEQUENCE would pass every other test here.
    //
    // It still matters: an undo restores the whole definition as one value, so
    // the literal vector comes back in its original sequence, and that is what
    // a persistence format (P16-PERSIST-001) or a CLI listing would write out.
    Part part;
    CommandHistory history;
    const MeshControlId control = makeControl(part, history);

    // Added in an order that is NOT the sorted order, or this test would be
    // comparing a sorted vector with itself: a Side face sorts after an end
    // cap, and entity 5 before entity 7.
    const std::array<FaceName, 3> faces{part.side(2), part.top(), part.side(0)};
    for (const FaceName& face : faces) {
        (void)run<AddLocalMeshSizingCommand>(history, part.document, control, face, 2_mm);
    }

    const std::vector<LocalMeshSizing> stored =
        definitionOf(part.document, control).mesh.sizing.local;
    REQUIRE(stored.size() == 3U);
    REQUIRE(stored.front().face == faces[0]);
    REQUIRE_FALSE(stored ==
                  meshing::findMeshControl(part.document, control)->orderedLocalSizing());

    // Remove the middle one and put it back.
    (void)run<RemoveLocalMeshSizingCommand>(history, part.document, control, faces[1]);
    REQUIRE(definitionOf(part.document, control).mesh.sizing.local.size() == 2U);
    requireUndo(history, part.document);
    CHECK(definitionOf(part.document, control).mesh.sizing.local == stored);

    // And the sorted enumeration is unchanged by any of it, which is the
    // contract a later format depends on.
    const std::vector<LocalMeshSizing> ordered =
        meshing::findMeshControl(part.document, control)->orderedLocalSizing();
    REQUIRE(ordered.size() == 3U);
    for (std::size_t i = 1U; i < ordered.size(); ++i) {
        INFO("position " << i);
        CHECK((ordered[i - 1U].face <=> ordered[i].face) == std::strong_ordering::less);
    }
}

// ---------------------------------------------------------------------------
// Where a command's geometry reference comes from
// ---------------------------------------------------------------------------
//
// A user may start a sizing edit from a CAD face or from a facet of the
// generated mesh. Both must end up storing THE SAME canonical reference,
// because the mesh-originated path is only a way of naming a CAD face -- and
// if it stored anything mesh-local the control would be wrong at the next
// remesh. These two tests are the mapping integration this milestone depends
// on, and the second is the case that must be refused outright.

TEST_CASE("MeshingCommand_AMeshOriginatedEditStoresTheSameReferenceAsACadOriginatedOne",
          "[meshing][meshcmd][reference]") {
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    const GeometryMeshMap* map = mesher.map(control);
    REQUIRE(map != nullptr);
    const meshing::Mesh& mesh = mesher.mesh(control)->mesh();

    // Pick a boundary facet and ask the MAP what CAD face it came from. This
    // is the resolution a GUI must do before building a command: the facet
    // identity goes no further than this call.
    std::optional<FaceName> resolved;
    meshing::ElementId chosen{};
    for (const meshing::Triangle& facet : mesh.triangles()) {
        const Result<meshing::FacetSource> source = meshing::sourceFaceOf(*map, facet.id);
        if (source.has_value() && !source->names.empty()) {
            resolved = source->names.front();
            chosen = facet.id;
            break;
        }
    }
    REQUIRE(resolved.has_value());
    INFO("from facet " << chosen.value());

    // The command stores THAT, and nothing about the facet.
    (void)run<AddLocalMeshSizingCommand>(history, part.document, control, *resolved, 2_mm);
    const LocalMeshSizing* stored =
        meshing::findMeshControl(part.document, control)->localSizing(*resolved);
    REQUIRE(stored != nullptr);
    CHECK(stored->face == *resolved);

    // AND IT IS A REFERENCE THE CAD SIDE COULD HAVE PRODUCED. Every FaceName
    // the map attributes is one of the feature's own names, so the two entry
    // paths are the same path after resolution -- which is what makes a
    // mesh-originated control survive a remesh.
    const std::array<FaceName, 3> cadNames{part.top(), part.bottom(), part.side(0)};
    const bool namedFromCad =
        std::ranges::any_of(cadNames, [&resolved](const FaceName& name) {
            return name == *resolved;
        }) ||
        resolved->feature == part.feature;
    CHECK(namedFromCad);
    CHECK(resolved->feature == part.feature);

    // Undo and redo move it unchanged, as for any other reference.
    requireUndo(history, part.document);
    requireRedo(history, part.document);
    CHECK(meshing::findMeshControl(part.document, control)->localSizing(*resolved)->face ==
          *resolved);
}

TEST_CASE("MeshingCommand_AnInteriorMeshFaceCannotNameASizingTarget",
          "[meshing][meshcmd][reference]") {
    // THE REFUSAL THAT HAS TO COME FIRST. A face shared by two tetrahedra has
    // no CAD boundary face, so there is no reference for a command to store --
    // and the map says so instead of offering the nearest exterior face.
    // Without this, a click on an interior face of a cut-away view would
    // silently refine whichever outside face happened to be closest.
    Part part;
    CommandHistory history;
    Mesher mesher;
    const MeshControlId control = makeControl(part, history);
    REQUIRE(mesher.generate(part.document, part.regenerator, control).has_value());
    const GeometryMeshMap* map = mesher.map(control);
    REQUIRE(map != nullptr);
    const meshing::Mesh& mesh = mesher.mesh(control)->mesh();

    std::optional<Error> refusal;
    for (const meshing::Tetrahedron& tet : mesh.tetrahedra()) {
        for (std::size_t ordinal = 0U; ordinal < 4U; ++ordinal) {
            const Result<meshing::FacetSource> source = meshing::sourceFaceOf(
                *map, mesh, meshing::TetrahedronFace{.tetrahedron = tet.id, .ordinal = ordinal});
            if (!source.has_value()) {
                refusal = source.error();
                break;
            }
        }
        if (refusal.has_value()) {
            break;
        }
    }
    // A tetrahedralisation of a solid has interior faces, or it is one
    // tetrahedron -- and the fixture's is not.
    REQUIRE(mesh.tetrahedra().size() > 1U);
    REQUIRE(refusal.has_value());
    CHECK(refusal->code == ErrorCode::FailedPrecondition);

    // So nothing was added, and the document is untouched by the attempt.
    CHECK(definitionOf(part.document, control).mesh.sizing.local.empty());
    CHECK(history.undoCount() == 1U);
}
