@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P16-QUAL-001 -- the FINAL qualification of P16 - Meshing. The exact
rem invocation, recorded so the run is reproducible rather than described.
rem
rem qualify.cmd is carried UNCHANGED from P15-QUAL-001, byte for byte
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b);
rem verify-harness.cmd beside it is its regression and is meant to be run
rem whenever it is edited, which it was not.
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of nearly 600 template-heavy
rem translation units exhausted the commit charge -- "cc1plus.exe: out of
rem memory allocating 4198399 bytes", at object 286 of 592. ONE resource
rem failure became FIVE failed stages there. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE BLAST RADIUS OF A QUALIFICATION MILESTONE.
rem
rem This milestone changed NO PRODUCTION CODE. The candidate's eight-path
rem fingerprint differs from P16-REFMOD-001's in `tests` alone:
rem
rem   apps      b4972247   unchanged      examples  75ce1c68   unchanged
rem   include   528df72c   unchanged      cmake     5a382115   unchanged
rem   src       182a584b   unchanged      CMakeLists.txt / CMakePresets.json
rem   tests     e6173c6f   MOVED                     unchanged
rem
rem What moved is one new test file -- the final cross-milestone gates -- plus
rem its registration and one more filter in the zero-match guard. The ADR-031
rem amendment is in docs/, which is outside the fingerprint by construction.
rem
rem So the determinism set is P16-REFMOD-001's, which is already the widest in
rem the phase, plus this milestone's own gates:
rem
rem   unit\.P16Qualification  the five FINAL gates: the authority matrix as one
rem                           executable statement, persistence independence
rem                           from mesh DENSITY, surface orientation
rem                           determinism, the stale-geometry sequence
rem                           including a failed regeneration, and the
rem                           breadth round-trip of all nine documents
rem   unit\.Mesh              every meshing and mesh-renderer test, AND
rem                           P16-REFMOD-001's 28 cases, which all begin "Mesh"
rem   unit\.Siz               the sizing module
rem   unit\.Volume            the volume mesh contract
rem   unit\.Netgen            the backend
rem   unit\.Surface           the boundary the backend is given
rem   unit\.Tet               element validation
rem   unit\.ReferenceModel    the twelve mechanical parts (P11/P12)
rem   unit\.AssemblyReference the eight assemblies (P13)
rem   unit\.DrawingReference  the seven drawings (P14)
rem   unit\.MaterialReference the eight material models (P15)
rem   unit\.Analytic          the independent geometry toolkit's own tests
rem   refmod\.                every reference-model process test
rem   cli\.                   every cli test
rem   gui\.                   the application links the same meshing module
rem   architecture            containment, including the backend rule
rem
rem Measured on the previous milestone: 692 tests, 686 s for five repeats in
rem release-ext and 722 s in debug-ext. This candidate adds five.
rem
rem compile_fail is excluded: this milestone adds no compile-fail case, and
rem nothing in tests/qualification/ is included by one. Each of those cases is
rem a real compilation, so five rounds of roughly two hundred would cost about
rem two hours and report nothing about the final gates. P16-CMD-001 included
rem them because it added thirteen.
rem
rem It is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%: a %VAR%
rem holding | ( or ) is substituted when the for-block is PARSED and closes the
rem block early, killing the run after every preset has already passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=unit\.P16Qualification|unit\.Mesh|unit\.Siz|unit\.Volume|unit\.Netgen|unit\.Surface|unit\.Tet|unit\.ReferenceModel|unit\.AssemblyReference|unit\.DrawingReference|unit\.MaterialReference|unit\.Analytic|refmod\.|cli\.|gui\.|architecture"
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
