@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P17-DATA-001 -- Analysis / Result Data Model. The exact invocation,
rem recorded so the run is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, twelve in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and is meant to be run
rem whenever it is edited, which it was not.
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of nearly 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE BLAST RADIUS, AND IT IS THE WHOLE REPOSITORY.
rem
rem This milestone adds a module's worth of structural types, and it also
rem touches TWO HEADERS THAT ALMOST EVERYTHING INCLUDES:
rem
rem   include/bettercad/core/Id.hpp          three new tags, three aliases and
rem                                          one isDocumentObjectTag
rem                                          specialisation
rem   include/bettercad/core/math/Vector.hpp one new struct, three operators,
rem                                          one free function, one #include
rem
rem Both changes are purely ADDITIVE -- no existing declaration moved, no
rem semantics changed, nothing was removed -- but "additive to a header
rem everything includes" is still a change whose reach is total, and the
rem repeat set is chosen for the reach rather than for the diff.
rem
rem   architecture             containment and layering over 453 files, plus
rem                            the 13 checker self-tests
rem   unit\.Structural         this milestone's 21 data tests and P17-ARCH's 10
rem                            input-boundary tests
rem   unit\.Id                 core's own identity tests, which are what the
rem                            Id.hpp change could break
rem   unit\.Unit, unit\.Quantity  the units framework Vector.hpp builds on
rem   unit\.Mesh               every meshing and mesh-renderer test, AND
rem                            P16-REFMOD-001's 28 reference cases, which all
rem                            begin "Mesh"
rem   unit\.Volume, unit\.Siz  the volume mesh and sizing contracts the result
rem                            model's provenance depends on
rem   unit\.Material, unit\.Mass  P15's material resolution, which
rem                            currentResultSource consumes, and the other
rem                            consumer of the same contract
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12), which
rem                            exercise ObjectId and the ID machinery hardest
rem   unit\.Analytic           the independent geometry toolkit's own tests
rem   refmod\.                 every reference-model process test
rem   gui\.                    the application links the library whose core
rem                            headers moved
rem
rem compile_fail is excluded from the REPEAT, and the reason is specific rather
rem than convenience. This milestone adds twelve compile-fail cases and they
rem matter -- they are the proof of the identity model -- but each is a real
rem COMPILATION, so what repeating one five times measures is the compiler's
rem determinism and not BetterCAD's. Forty-seven identity-related cases over
rem five rounds in two presets would cost about three quarters of an hour and
rem report nothing. They run UNFILTERED in all three presets, which is where a
rem compile-fail regression is caught.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Structural|unit\.Id|unit\.Unit|unit\.Quantity|unit\.Mesh|unit\.Volume|unit\.Siz|unit\.Material|unit\.Mass|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
