@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P17-LOAD-001 -- Structural Loads. The exact invocation, recorded so the run
rem is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, sixteen in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and was not edited
rem (11855b8ff891093b021d1e0351761283d0eedd24).
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of over 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE BLAST RADIUS IS WIDER THAN THE LAST TWO MILESTONES', and the reason is
rem recorded rather than glossed: this one touches `core`. Traction3D and
rem Moment3D went into core/math/Vector.hpp beside Force3D, and Torque into
rem core/units/Units.hpp beside Stress, because that is the placement Force3D's
rem own comment establishes for an engineering quantity. Everything that
rem includes core is therefore in reach, exactly as it was for P17-DATA-001
rem when it added Force3D. The repeat set is the broad one for that reason, not
rem out of habit:
rem
rem   unit\.Unit, unit\.Quantity
rem                            the unit system itself, which gained an alias.
rem                            A Quantity is keyed on its DIMENSION, so Torque
rem                            and Energy are the same type -- and a change to
rem                            the dimension algebra would reach every
rem                            engineering quantity in the tree
rem   unit\.Structural         this milestone's 23 (unit\.Structural matches
rem                            StructuralLoad_*, which was VERIFIED by counting
rem                            them inside the selection rather than by reading
rem                            the filter), plus P17-ELEM's, P17-MAT's,
rem                            P17-DATA's and P17-ARCH's. The analysis
rem                            DEFINITION changed here -- it now carries the
rem                            loads -- so P17-DATA's currentness tests are
rem                            directly in reach
rem   unit\.Tet4Element        P17-ELEM's 29. It shares the signed-volume
rem                            contract this milestone integrates gravity over
rem   unit\.Mesh, unit\.Volume, unit\.Tet
rem                            P16's MAPPING AND ORIENTATION contract, which is
rem                            the load module's load-bearing dependency: every
rem                            face target is resolved by boundaryFacetsOf, and
rem                            pressure's sign rests on the boundary winding
rem                            being outward. Also matches P16-REFMOD-001's
rem                            reference cases, which all begin "Mesh"
rem   unit\.MeshDofMap, unit\.ConstraintSet, unit\.FreeEquationMap
rem                            P17-DOF's, which share the MeshStamp binding
rem                            discipline the nodal-force policy uses
rem   unit\.Material, unit\.Mass
rem                            P15's density, which gravity consumes through
rem                            StructuralMaterial. A change to the derivation
rem                            is a change to every weight this module computes
rem   unit\.Id                 the identity machinery; LoadId is reused here
rem   architecture             containment and layering over the whole tree,
rem                            because two new public headers went into an
rem                            existing module and core gained two types
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12)
rem   unit\.Analytic           the independent geometry toolkit's own tests
rem   refmod\.                 every reference-model process test
rem   gui\.                    the application links the structural library
rem
rem compile_fail is excluded from the REPEAT for the reason the previous five
rem milestones recorded: each case is a real COMPILATION, so repeating one
rem measures the compiler's determinism and not BetterCAD's. Every case still
rem runs UNFILTERED in all three presets, which is where a compile-fail
rem regression is caught.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Tet4Element|unit\.Structural|unit\.MeshDofMap|unit\.ConstraintSet|unit\.FreeEquationMap|unit\.Material|unit\.Mass|unit\.Mesh|unit\.Volume|unit\.Tet|unit\.Siz|unit\.Id|unit\.Unit|unit\.Quantity|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
