@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P17-DOF-001 -- DOF Numbering / Constraint Model. The exact invocation,
rem recorded so the run is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, fourteen in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and was not edited
rem (11855b8ff891093b021d1e0351761283d0eedd24).
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of nearly 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE BLAST RADIUS. This milestone adds one header, one translation unit and
rem three test files, all inside structural/ and its tests, and changes no
rem existing production file. Nothing in the tree calls the new code yet, so
rem the reach is not downstream -- it is UPSTREAM, towards the two contracts
rem the numbering is derived from, and the repeat set is chosen for those:
rem
rem   unit\.Mesh               P16's MESH ENUMERATION CONTRACT, which is the
rem                            load-bearing dependency of the whole milestone:
rem                            the node ordinal IS the index into
rem                            mesh.nodes(), and Mesh guarantees that order is
rem                            ascending by NodeId with no unordered container.
rem                            A change there changes every DOF index. Also
rem                            matches P16-REFMOD-001's reference cases, which
rem                            all begin "Mesh", including the four this
rem                            milestone integrates against
rem   unit\.Volume, unit\.Siz  the volume mesh and sizing contracts the
rem                            reference integration meshes through
rem   unit\.MeshDofMap, unit\.ConstraintSet, unit\.FreeEquationMap
rem                            THREE TERMS ADDED FOR THIS MILESTONE, because the
rem                            inherited set missed 14 of its 31 tests: only
rem                            StructuralDof_* matched unit\.Structural, and
rem                            MeshDofMap_* matched unit\.Mesh by accident, so a
rem                            determinism stage run on the inherited filter would
rem                            have repeated 751 tests and claimed a set it had not
rem                            covered. Checked by counting the milestone own tests
rem                            INSIDE the selection, not by reading the filter
rem   unit\.Structural         this milestone's 31, P17-MAT's 19, P17-DATA's
rem                            21, P17-ARCH's 10. P17-DATA's StructuralResult
rem                            keys its displacement array by the SAME ordinal,
rem                            and a test asserts the two agree
rem   unit\.Id, unit\.Unit, unit\.Quantity
rem                            the identity machinery the claim rests on:
rem                            neither DofIndex nor FreeEquationIndex is a
rem                            document identity, and NodeId is not an index
rem   architecture             containment and layering over the whole tree,
rem                            because a new public header went into an
rem                            existing module
rem   unit\.Material, unit\.Mass
rem                            carried from P17-MAT-001 rather than dropped.
rem                            This milestone cannot reach them, and running
rem                            them costs minutes; removing them would narrow
rem                            the set on an argument -- that a new file in
rem                            structural/ cannot affect P15 -- which the
rem                            unfiltered full-suite stage already tests
rem                            better
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12)
rem   unit\.Analytic           the independent geometry toolkit's own tests
rem   refmod\.                 every reference-model process test
rem   gui\.                    the application links the structural library
rem
rem compile_fail is excluded from the REPEAT for the reason the previous three
rem milestones recorded: each case is a real COMPILATION, so repeating one
rem measures the compiler's determinism and not BetterCAD's. The nine new
rem structural DOF cases and the twelve identity cases still run UNFILTERED in
rem all three presets, which is where a compile-fail regression is caught.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Structural|unit\.ConstraintSet|unit\.FreeEquationMap|unit\.MeshDofMap|unit\.Material|unit\.Mass|unit\.Mesh|unit\.Volume|unit\.Siz|unit\.Id|unit\.Unit|unit\.Quantity|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
