@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem
rem The tree being frozen is not the only thing that must hold still during a
rem qualification. So must the script driving it.
rem ---------------------------------------------------------------------
rem
rem P16-VIZ-001 qualification: the exact invocation, recorded so the run is
rem reproducible rather than described.
rem
rem qualify.cmd is carried UNCHANGED from P15-QUAL-001, byte for byte
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b);
rem verify-harness.cmd beside it is its regression and is meant to be run
rem whenever it is edited, which it was not.
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried from INFRA-VIEWER-001 and for the
rem same reason: this machine has 16 logical cores, so `cmake --build` lets
rem Ninja run 18 compiles at once, and a CLEAN build of 592 template-heavy
rem translation units exhausted the commit charge -- "cc1plus.exe: out of
rem memory allocating 4198399 bytes", at object 286 of 592. ONE resource
rem failure became FIVE failed stages there. Capping parallelism weakens
rem nothing: the same sources are compiled with the same flags, -Werror
rem included, the no-op rebuild check still proves the binaries are the ones
rem just built, the full suite still runs in all three presets, and the
rem determinism stages still repeat five times. Only the number of compilers
rem running at once changes. ctest stays at -j 8.
rem
rem THE REPEAT FILTER IS THE BLAST RADIUS. This milestone adds a renderer
rem module's worth of mesh visualisation and changes the desktop application,
rem so the determinism set is:
rem
rem   unit\.Mesh             every mesh view, inspection, scene and display
rem                          test, plus the meshing module's own -- the
rem                          adapter reads MeshQualityReport and
rem                          GeometryMeshMap, so a change in either would
rem                          surface here
rem   unit\.Viewer_          INFRA-VIEWER-001's viewer, which now has a mesh
rem                          display path through the same AIS context
rem   unit\.RenderedImage_   the coverage measure every rendering assertion
rem                          rests on
rem   unit\.StandardView_    the camera names the inspector navigates with
rem   gui\.                  the launch smoke test and the ten mesh claims
rem   compile_fail           the identity confusions and the viewer group
rem   architecture           what would notice OCCT or Qt escaping, and the
rem                          renderer's new dependency on meshing
rem
rem It is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%: a %VAR%
rem holding | ( or ) is substituted when the for-block is PARSED and closes the
rem block early, killing the run after every preset has already passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=unit\.Mesh|unit\.Viewer_|unit\.RenderedImage_|unit\.StandardView_|gui\.|compile_fail|architecture"
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
