@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P17-BC-001 -- Structural Restraints. The exact invocation, recorded so the
rem run is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, seventeen in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and was not edited
rem (11855b8ff891093b021d1e0351761283d0eedd24).
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of over 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE BLAST RADIUS IS NARROWER THAN P17-LOAD-001'S, and the difference is
rem stated rather than the broad filter carried out of habit. That milestone
rem touched `core` -- Traction3D, Moment3D and Torque went into
rem core/math/Vector.hpp and core/units/Units.hpp -- so everything including
rem core was in reach. THIS milestone touches no file outside
rem src/structural/, include/bettercad/structural/ and tests/. The unit system
rem gained nothing, so unit\.Unit and unit\.Quantity are NOT in the repeat set;
rem no material code changed, so unit\.Material and unit\.Mass are not either.
rem Both still run unfiltered in all three presets, which is where a change
rem nobody predicted is caught.
rem
rem What IS in reach, and why:
rem
rem   unit\.Structural         this milestone's 32 (24 unit + 8 reference,
rem                            VERIFIED by counting StructuralBC_ inside the
rem                            selection rather than by reading the filter --
rem                            P17-DOF-001 found a filter that covered 17 of
rem                            31 tests), plus P17-LOAD's 23, P17-ELEM's,
rem                            P17-MAT's, P17-DATA's and P17-ARCH's.
rem                            src/structural/StructuralLoad.cpp CHANGED here:
rem                            its three mapping checks moved to the shared
rem                            structural::resolveFaceTarget, so P17-LOAD-001
rem                            is requalified by this run and its 23 tests are
rem                            the direct evidence. The analysis DEFINITION
rem                            changed too -- it now carries the restraints --
rem                            so P17-DATA's currentness tests are in reach
rem   unit\.MeshDofMap, unit\.ConstraintSet, unit\.FreeEquationMap
rem                            P17-DOF's. This milestone CONSUMES all three:
rem                            every constrained index comes from
rem                            MeshDofMap::indexOf and the set is P17-DOF's own
rem                            ConstraintSet, built through buildConstraintSet
rem   unit\.Tet4Element        P17-ELEM's. Same module and same library; it
rem                            shares no code with this milestone, and is
rem                            repeated because a link-order or export change
rem                            in bettercad_structural would reach it
rem   unit\.Mesh, unit\.Volume, unit\.Tet
rem                            P16's MAPPING contract, which is this module's
rem                            load-bearing dependency: every target is
rem                            resolved by boundaryFacetsOf and every node set
rem                            comes from boundaryNodesOf, whose sort-and-
rem                            unique is what this milestone deliberately does
rem                            NOT reimplement. Also matches P16-REFMOD-001's
rem                            reference cases, which all begin "Mesh"
rem   unit\.Siz                P16-SIZE's. The unit fixture and the RM-MESH-07
rem                            case both drive LOCAL sizing, and the
rem                            RM-MESH-02 case drives surface deflection
rem   unit\.Id                 the identity machinery; RestraintId is used here
rem                            and the compile-fail group structids asserts it
rem                            is not interchangeable with a NodeId
rem   architecture             containment and layering over the whole tree,
rem                            because THREE new public headers went into an
rem                            existing module
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12)
rem   unit\.Analytic           the independent geometry toolkit's own tests
rem   refmod\.                 every reference-model process test
rem   gui\.                    the application links the structural library
rem
rem compile_fail is excluded from the REPEAT for the reason the previous six
rem milestones recorded: each case is a real COMPILATION, so repeating one
rem measures the compiler's determinism and not BetterCAD's. All six new cases
rem still run UNFILTERED in all three presets, which is where a compile-fail
rem regression is caught.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Structural|unit\.MeshDofMap|unit\.ConstraintSet|unit\.FreeEquationMap|unit\.Tet4Element|unit\.Mesh|unit\.Volume|unit\.Tet|unit\.Siz|unit\.Id|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
