@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem CORRECTED 2026-10-10 by P17-POST-001, AFTER this milestone had passed.
rem
rem This file carried 1 bare `OLD_END` line -- a heredoc terminator
rem leaked by the session that wrote it -- in the middle of the comment block
rem below. cmd.exe reported "'OLD_END' is not recognized as an internal or
rem external command" for each, and run-qualification.err beside this file
rem STILL RECORDS THAT, because it is the record of what the run actually
rem produced and is not edited.
rem
rem THE RUN WAS NOT AFFECTED. An unrecognized command prints to stderr and
rem cmd.exe carries on; every stage still recorded exit 0, the stage table and
rem the test counts in this milestone's README are unchanged, and the qualified
rem source fingerprint is unchanged -- this file is documentation and is
rem outside the eight fingerprinted paths. Nothing in the qualification result
rem moves because of this correction.
rem
rem What changed: the bare line was removed, and this note added. A file that
rem calls itself "the exact invocation" must not contain lines that are not
rem part of it.
rem
rem P17-ASSEMBLY-001 -- Global Matrix / Vector Assembly. The exact invocation,
rem recorded so the run is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, eighteen in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and was not edited
rem (11855b8ff891093b021d1e0351761283d0eedd24).
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of over 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE BLAST RADIUS IS THE NARROWEST OF ANY P17 MILESTONE SO FAR, and it is
rem stated rather than the broad filter carried out of habit. NO PREDECESSOR
rem PRODUCTION FILE WAS MODIFIED: `git status` over src and include shows two
rem NEW files and a one-line addition to src/structural/CMakeLists.txt
rem registering one of them. So brief section 146's requalification requirement
rem has nothing to act on, and the repeat set is chosen for what this milestone
rem CONSUMES rather than for what it changed.
rem
rem The unit system gained nothing, so unit\.Unit and unit\.Quantity are NOT in
rem the set; no material or load code changed, so unit\.Material and unit\.Mass
rem are not either. Everything still runs unfiltered in all three presets,
rem which is where a change nobody predicted is caught.
rem
rem What IS in reach, and why:
rem
rem   unit\.Structural         this milestone's 26 (20 unit + 6 reference,
rem                            VERIFIED by counting StructuralSystem_ inside
rem                            the selection rather than by reading the filter
rem                            -- P17-DOF-001 found a filter that covered 17 of
rem                            31 tests), plus P17-BC's 32, P17-LOAD's 23,
rem                            P17-ELEM's, P17-MAT's, P17-DATA's and
rem                            P17-ARCH's. All four of those are CONSUMED here:
rem                            Ke from P17-ELEM, the numbering and the free
rem                            equations from P17-DOF, the nodal forces from
rem                            P17-LOAD, and the restraint independence of the
rem                            unconstrained system from P17-BC
rem   unit\.MeshDofMap, unit\.ConstraintSet, unit\.FreeEquationMap
rem                            P17-DOF's. The global ROW SPACE is the free
rem                            numbering of the empty constraint set, so all
rem                            three are on the assembly's critical path: a
rem                            change to equationOf would move every row
rem   unit\.Tet4Element        P17-ELEM's 29. Every global entry is a sum of
rem                            Ke entries, so a change to the element
rem                            formulation changes every matrix this milestone
rem                            produces -- the most directly coupled
rem                            predecessor there is
rem   unit\.Mesh, unit\.Volume, unit\.Tet
rem                            P16's MAPPING contract, which is this module's
rem                            load-bearing dependency: every target is
rem                            resolved by boundaryFacetsOf and every node set
rem                            comes from boundaryNodesOf, whose sort-and-
rem                            unique is what this milestone deliberately does
rem                            NOT reimplement. Also matches P16-REFMOD-001's
rem                            reference cases, which all begin "Mesh"
rem   unit\.Siz                P16-SIZE's. The unit fixture and the RM-MESH-07
rem                            case both drive LOCAL sizing, and the large-mesh
rem                            fixture drives surface deflection to 0.025 mm
rem   unit\.Id                 the identity machinery
rem   architecture             containment and layering over the whole tree,
rem                            because a new public header went into an
rem                            existing module
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12)
rem   unit\.Analytic           the independent geometry toolkit's own tests
rem   refmod\.                 every reference-model process test
rem   gui\.                    the application links the structural library
rem
rem compile_fail is excluded from the REPEAT for the reason the previous seven
rem milestones recorded: each case is a real COMPILATION, so repeating one
rem measures the compiler's determinism and not BetterCAD's. All six new cases
rem still run UNFILTERED in all three presets, which is where a compile-fail
rem regression is caught.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Structural|unit\.MeshDofMap|unit\.ConstraintSet|unit\.FreeEquationMap|unit\.Tet4Element|unit\.Mesh|unit\.Volume|unit\.Tet|unit\.Siz|unit\.Id|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
