# Configure-time report of the toolchain and enabled components.
include_guard(GLOBAL)

function(_bettercad_summary_line label value)
    string(LENGTH "${label}" len)
    math(EXPR pad "22 - ${len}")
    string(REPEAT " " ${pad} spaces)
    message(STATUS "  ${label}${spaces}: ${value}")
endfunction()

function(bettercad_print_summary)
    get_property(multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if(multi_config)
        set(build_type "multi-config (${CMAKE_CONFIGURATION_TYPES})")
    else()
        set(build_type "${CMAKE_BUILD_TYPE}")
    endif()

    if(BETTERCAD_GUI_ENABLED)
        set(gui "ON (Qt ${Qt6_VERSION}, ${Qt6_DIR})")
    else()
        set(gui "OFF (BETTERCAD_BUILD_GUI=${BETTERCAD_BUILD_GUI})")
    endif()
    if(BETTERCAD_BUILD_TESTS)
        set(tests "ON (Catch2 ${BETTERCAD_CATCH2_VERSION})")
    else()
        set(tests "OFF")
    endif()
    if(EXISTS "${BETTERCAD_DEPS_PREFIX}")
        set(deps "${BETTERCAD_DEPS_PREFIX}")
    else()
        set(deps "${BETTERCAD_DEPS_PREFIX} (not present)")
    endif()

    message(STATUS "")
    message(STATUS "BetterCAD ${PROJECT_VERSION} configuration")
    _bettercad_summary_line("CMake" "${CMAKE_VERSION} (${CMAKE_GENERATOR})")
    _bettercad_summary_line("C++ compiler" "${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
    _bettercad_summary_line("Compiler path" "${CMAKE_CXX_COMPILER}")
    _bettercad_summary_line("C++ standard" "C++${CMAKE_CXX_STANDARD}")
    _bettercad_summary_line("Target platform" "${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_PROCESSOR}")
    _bettercad_summary_line("Build type" "${build_type}")
    _bettercad_summary_line("Shared libraries" "${BUILD_SHARED_LIBS}")
    _bettercad_summary_line("Warnings as errors" "${BETTERCAD_WARNINGS_AS_ERRORS}")
    _bettercad_summary_line("CLI" "${BETTERCAD_BUILD_CLI}")
    _bettercad_summary_line("Desktop app" "${gui}")
    _bettercad_summary_line("Tests" "${tests}")
    _bettercad_summary_line("Dependency prefix" "${deps}")
    message(STATUS "")
endfunction()
