@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem
rem EVERY LINE OF THIS FILE BEGINS WITH rem, set, call, echo, setlocal,
rem endlocal OR @echo, AND THAT IS CHECKED BEFORE THE RUN. P17-ASSEMBLY-001's
rem and P17-SOLVE-001's copies each carried bare OLD_END lines -- leaked
rem heredoc terminators -- which cmd.exe reported into their .err files. They
rem were corrected by P17-POST-001 and the check is now part of the freeze.
rem ---------------------------------------------------------------------
rem
rem P17-VALID-001 -- Structural Validation / Acceptance. The exact invocation,
rem recorded so the run is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, TWENTY-TWO in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and was not edited
rem (11855b8ff891093b021d1e0351761283d0eedd24).
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of over 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem WHAT CHANGED, AND WHAT IS OWED BY IT.
rem
rem   NEW          include/bettercad/structural/StructuralValidation.hpp
rem                src/structural/StructuralValidation.cpp
rem                tests/structural/StructuralValidationTests.cpp
rem                tests/reference/StructuralValidationSweepTests.cpp
rem                tests/compile_fail/StructuralValidationMisuse.cpp
rem   MODIFIED     src/structural/CMakeLists.txt     the new source, nothing
rem                                                  else
rem                tests/CMakeLists.txt              two registrations
rem                tests/compile_fail/CMakeLists.txt one group, six cases
rem
rem NO PREDECESSOR PRODUCTION FILE WAS MODIFIED, which is the difference from
rem P17-REACTION-001: that milestone had to add a field to qualified P17-BC
rem code, and this one needed nothing that was not already public. In
rem particular no MESHING source file changed -- P16 remains report-only, its
rem reportOnlyThresholds() still classifies nothing, and the P17 policy is a
rem QualityThresholds VALUE handed to evaluateMeshQuality rather than a change
rem to it.
rem
rem NO SHARED TEST INFRASTRUCTURE CHANGED. tests/architecture/CheckLayering.cmake
rem is byte-identical to P17-REACTION-001's; architecture is in the repeat set
rem because a new public header went into an existing module.
rem
rem What IS in reach, and why:
rem
rem   unit\.Structural         this milestone's 32 (27 unit + 5 reference),
rem                            VERIFIED by counting TEST_CASE in both files
rem                            AND by the suite total moving from 3721 to
rem                            3759 -- the two ends agree on 38 with the six
rem                            compile-failure cases, which are NOT in this
rem                            filter and run unfiltered.
rem
rem                            Plus P17-REACTION's 21, P17-POST's 41,
rem                            P17-SOLVE's 25, P17-ASSEMBLY's 26, P17-BC's 32,
rem                            P17-LOAD's 23, P17-ELEM's 29, and P17-MAT's,
rem                            P17-DATA's and P17-ARCH's. Every one of them is
rem                            a consumer: this milestone's entry point calls
rem                            the whole chain in order.
rem   unit\.Quality            P16-QUALITY's 56. THE LARGEST SINGLE DEBT OF
rem                            THIS MILESTONE. The policy is a
rem                            QualityThresholds value consumed by
rem                            evaluateMeshQuality, classified by P16's own
rem                            direction(metric), and read out of
rem                            MeshQualityReport::summaries -- so a change to
rem                            any metric, to the summary extrema, to the
rem                            strictness of a comparison or to validate()
rem                            moves every threshold in this milestone.
rem                            Counted: 56 TEST_CASEs across seven prefixes,
rem                            all of which begin with Quality.
rem   unit\.MeshDofMap, unit\.ConstraintSet, unit\.FreeEquationMap
rem                            P17-DOF's. The constrained-degree-of-freedom
rem                            COUNT is a refusal in this milestone, so a
rem                            change to how a ConstraintSet is built changes
rem                            a verdict.
rem   unit\.Tet4Element        P17-ELEM's. The two accuracy laws are measured
rem                            THROUGH recoverElementFields, which is the
rem                            kernel, so the thresholds are derived from this
rem                            module's arithmetic.
rem   unit\.Mesh, unit\.Volume, unit\.Tet
rem                            P16's enumeration, node positions and signed
rem                            volume. The structural verdict is P16-DATA's
rem                            and is reused unchanged.
rem   unit\.Siz                P16-SIZE's. Every document fixture here drives
rem                            a global target size, and the thin-plate
rem                            fixture depends on what 20 mm produces on a
rem                            0.5 mm plate.
rem   unit\.Id                 the identity machinery.
rem   architecture             containment and layering over the whole tree.
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12).
rem   unit\.Analytic           the independent geometry toolkit's own tests.
rem   refmod\.                 every reference-model process test. The quality
rem                            sweep and the acceptance test read ALL SEVEN
rem                            P16 mesh reference models.
rem   gui\.                    the application links the structural library.
rem
rem The unit system gained nothing, so unit\.Unit and unit\.Quantity are NOT
rem in the set, and unit\.Material and unit\.Mass are not either: no material
rem code changed, and the mode-requirement check calls P17-MAT unchanged.
rem Everything still runs unfiltered in all three presets, which is where a
rem change nobody predicted is caught.
rem
rem compile_fail is excluded from the REPEAT for the reason the previous ten
rem milestones recorded: each case is a real COMPILATION, so repeating one
rem measures the compiler's determinism and not BetterCAD's. All six new cases
rem still run UNFILTERED in all three presets, and all six were additionally
rem run in debug-shared-ext BEFORE the freeze, with 38/38 passing there.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Structural|unit\.Quality|unit\.MeshDofMap|unit\.ConstraintSet|unit\.FreeEquationMap|unit\.Tet4Element|unit\.Mesh|unit\.Volume|unit\.Tet|unit\.Siz|unit\.Id|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
