@echo off
rem ---------------------------------------------------------------------
rem DO NOT EDIT THIS FILE WHILE IT IS RUNNING. NOT EVEN A COMMENT.
rem
rem cmd.exe reads a batch file INCREMENTALLY, BY BYTE OFFSET, as it executes
rem it. Changing the file's length mid-run moves everything after the cursor,
rem and execution resumes at an offset that no longer means what it meant.
rem
rem That cost INFRA-VIEWER-001 a four-hour qualification that had PASSED: two
rem minutes in, a comment was reworded; four hours later, when qualify.cmd
rem returned, cmd.exe resumed at a stale offset and called it a SECOND time,
rem truncating qualification-times.txt and overwriting three of debug-ext's
rem logs. The run had already printed "every stage exited 0" and the evidence
rem for it was gone.
rem ---------------------------------------------------------------------
rem
rem P17-ELEM-001 -- Tet4 Linear Elastic Element. The exact invocation,
rem recorded so the run is reproducible rather than described.
rem
rem qualify.cmd is byte-identical to the one P16-SIZE-001 settled on and every
rem milestone since has used, fifteen in a row counting this one
rem (git hash-object d313a64070718c44fae290ac042fe259d1a03c8b).
rem verify-harness.cmd beside it is its regression and was not edited
rem (11855b8ff891093b021d1e0351761283d0eedd24).
rem
rem CMAKE_BUILD_PARALLEL_LEVEL=6, carried for the reason INFRA-VIEWER-001
rem recorded: this machine has 16 logical cores, so `cmake --build` lets Ninja
rem run 18 compiles at once, and a CLEAN build of over 600 template-heavy
rem translation units exhausted the commit charge. Capping parallelism weakens
rem nothing: the same sources, the same flags, -Werror included; the no-op
rem rebuild check still proves the binaries are the ones just built; the full
rem suite still runs unfiltered in all three presets. ctest stays at -j 8.
rem
rem THE BLAST RADIUS. This milestone adds one header, one translation unit and
rem two test files, all inside structural/ and its tests, and changes no
rem existing production file. Nothing calls the new code yet, so the reach is
rem UPSTREAM -- towards the four contracts the element consumes -- and the
rem repeat set is chosen for those:
rem
rem   unit\.Tet4Element        THE TERM ADDED FOR THIS MILESTONE. Its 29 tests
rem                            match no inherited term: Tet4Element_* is
rem                            matched by neither unit\.Structural nor
rem                            unit\.Mesh. Verified by counting the
rem                            milestone's own tests INSIDE the selection, not
rem                            by reading the filter -- the same check that
rem                            caught a 14-test gap in P17-DOF-001
rem   unit\.Mesh, unit\.Volume, unit\.Tet
rem                            P16's SIGNED-VOLUME CONTRACT, which is the
rem                            load-bearing dependency: the element's validity
rem                            predicate is MeshValidation's rule, in its
rem                            order, with its classification, and the
rem                            determinant is grouped exactly as
rem                            meshing::signedVolume groups it so the two
rem                            agree bit for bit. A change there changes which
rem                            elements this kernel accepts. Also matches
rem                            P16-REFMOD-001's reference cases, which all
rem                            begin "Mesh", including the three this
rem                            milestone evaluates every element of
rem   unit\.Structural, unit\.MeshDofMap, unit\.ConstraintSet, unit\.FreeEquationMap
rem                            P17-DATA's Voigt ordering and Strain6/Stress6,
rem                            and P17-DOF's kDofsPerNode and offsetOf, which
rem                            localDofIndex is written in terms of so the
rem                            local and global DOF orders cannot drift
rem   unit\.Material, unit\.Mass
rem                            P15's LinearElasticConstants. mu is NOT
rem                            recomputed here -- it is P15's derived
rem                            shearModulus -- so a change to that derivation
rem                            is a change to every D this kernel builds
rem   unit\.Unit, unit\.Quantity, unit\.Id
rem                            the dimension algebra the Ke = V B^T D B
rem                            static_assert rests on, and the identity
rem                            machinery
rem   architecture             containment and layering over the whole tree,
rem                            because a new public header went into an
rem                            existing module
rem   unit\.ReferenceModel     the twelve mechanical parts (P11/P12)
rem   unit\.Analytic           the independent geometry toolkit's own tests
rem   refmod\.                 every reference-model process test
rem   gui\.                    the application links the structural library
rem
rem compile_fail is excluded from the REPEAT for the reason the previous four
rem milestones recorded: each case is a real COMPILATION, so repeating one
rem measures the compiler's determinism and not BetterCAD's. Every case still
rem runs UNFILTERED in all three presets, which is where a compile-fail
rem regression is caught.
rem
rem QUALIFY_REPEAT is expanded as !REPEAT! inside qualify.cmd, never %REPEAT%:
rem a %VAR% holding | ( or ) is substituted when the for-block is PARSED and
rem closes the block early, killing the run after every preset has passed.
setlocal
set "BETTERCAD_BUILD_ROOT=C:/Users/uqhas/AppData/Local/bc-build"
set "CMAKE_BUILD_PARALLEL_LEVEL=6"
set "QUALIFY_PRESETS=debug-ext release-ext debug-shared-ext"
set "QUALIFY_REPEAT_PRESETS=release-ext debug-ext"
set "QUALIFY_REPEAT=architecture|unit\.Tet4Element|unit\.Structural|unit\.MeshDofMap|unit\.ConstraintSet|unit\.FreeEquationMap|unit\.Material|unit\.Mass|unit\.Mesh|unit\.Volume|unit\.Tet|unit\.Siz|unit\.Id|unit\.Unit|unit\.Quantity|unit\.ReferenceModel|unit\.Analytic|refmod\.|gui\."
call "%~dp0qualify.cmd" "%~dp0."
set "RESULT=%errorlevel%"
echo qualify.cmd exit %RESULT%
endlocal & exit /b %RESULT%
